var searchData=
[
  ['enable_5fprofiling_105',['enable_profiling',['../class_legion_1_1_runtime.html#a357602aa4f54f88fe361861fa50e20a9',1,'Legion::Runtime']]],
  ['end_5fstatic_5ftrace_106',['end_static_trace',['../class_legion_1_1_runtime.html#ac89bdf19645572d9fd250156aad5a383',1,'Legion::Runtime']]],
  ['end_5ftrace_107',['end_trace',['../class_legion_1_1_runtime.html#ab8ac09dd81911b31e0569f41b9ef9668',1,'Legion::Runtime']]],
  ['execute_5findex_5fspace_108',['execute_index_space',['../class_legion_1_1_runtime.html#a0e8d31f02a06b0b63824d1eb9f79b4eb',1,'Legion::Runtime::execute_index_space(Context ctx, const IndexTaskLauncher &amp;launcher)'],['../class_legion_1_1_runtime.html#aa6f07a1164d549f044af6db3f0830008',1,'Legion::Runtime::execute_index_space(Context ctx, const IndexTaskLauncher &amp;launcher, ReductionOpID redop, bool deterministic=false)'],['../class_legion_1_1_runtime.html#a5ece93773965049ca5f025fe9c70a52b',1,'Legion::Runtime::execute_index_space(Context ctx, TaskID task_id, const Domain domain, const std::vector&lt; IndexSpaceRequirement &gt; &amp;indexes, const std::vector&lt; FieldSpaceRequirement &gt; &amp;fields, const std::vector&lt; RegionRequirement &gt; &amp;regions, const TaskArgument &amp;global_arg, const ArgumentMap &amp;arg_map, const Predicate &amp;predicate=Predicate::TRUE_PRED, bool must_paralleism=false, MapperID id=0, MappingTagID tag=0)'],['../class_legion_1_1_runtime.html#abfe61be1d1112821634f79d0d2bbc239',1,'Legion::Runtime::execute_index_space(Context ctx, TaskID task_id, const Domain domain, const std::vector&lt; IndexSpaceRequirement &gt; &amp;indexes, const std::vector&lt; FieldSpaceRequirement &gt; &amp;fields, const std::vector&lt; RegionRequirement &gt; &amp;regions, const TaskArgument &amp;global_arg, const ArgumentMap &amp;arg_map, ReductionOpID reduction, const TaskArgument &amp;initial_value, const Predicate &amp;predicate=Predicate::TRUE_PRED, bool must_parallelism=false, MapperID id=0, MappingTagID tag=0)']]],
  ['execute_5fmust_5fepoch_109',['execute_must_epoch',['../class_legion_1_1_runtime.html#a4f219e544094fa61ddea088645482e98',1,'Legion::Runtime']]],
  ['execute_5ftask_110',['execute_task',['../class_legion_1_1_runtime.html#a7b7d00659246b245b91410987e65eea0',1,'Legion::Runtime::execute_task(Context ctx, const TaskLauncher &amp;launcher)'],['../class_legion_1_1_runtime.html#a44cce1cf3ee372290521e61abacafc21',1,'Legion::Runtime::execute_task(Context ctx, TaskID task_id, const std::vector&lt; IndexSpaceRequirement &gt; &amp;indexes, const std::vector&lt; FieldSpaceRequirement &gt; &amp;fields, const std::vector&lt; RegionRequirement &gt; &amp;regions, const TaskArgument &amp;arg, const Predicate &amp;predicate=Predicate::TRUE_PRED, MapperID id=0, MappingTagID tag=0)']]]
];
