var searchData=
[
  ['safe_5fcast_0',['safe_cast',['../class_legion_1_1_runtime.html#a9158340668c0d8becc481ca648cc9782',1,'Legion::Runtime::safe_cast(Context ctx, DomainPoint point, LogicalRegion region)'],['../class_legion_1_1_runtime.html#a4184bff14eff459b500fc356da61a63c',1,'Legion::Runtime::safe_cast(Context ctx, Point&lt; DIM, COORD_T &gt; point, LogicalRegionT&lt; DIM, COORD_T &gt; region)']]],
  ['scaletransform_1',['ScaleTransform',['../struct_legion_1_1_scale_transform.html',1,'Legion']]],
  ['select_20close_20sources_2',['Select Close Sources',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_close_src_input.html#autotoc_md41',1,'']]],
  ['select_20copy_20sources_3',['Select Copy Sources',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_copy_src_input.html#autotoc_md35',1,'']]],
  ['select_20inline_20sources_4',['Select Inline Sources',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_inline_src_input.html#autotoc_md29',1,'']]],
  ['select_20partition_20projection_5',['Select Partition Projection',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_partition_projection_input.html#autotoc_md61',1,'']]],
  ['select_20partition_20sources_6',['Select Partition Sources',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_partition_src_input.html#autotoc_md65',1,'']]],
  ['select_20release_20sources_7',['Select Release Sources',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_release_src_input.html#autotoc_md55',1,'']]],
  ['select_20sharding_20functor_8',['select sharding functor',['../struct_legion_1_1_mapping_1_1_mapper_1_1_must_epoch_sharding_functor_output.html#autotoc_md79',1,'Select Sharding Functor'],['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_sharding_functor_input.html#autotoc_md25',1,'Select Sharding Functor'],['../class_legion_1_1_mapping_1_1_mapper.html#autotoc_md39',1,'Select Sharding Functor'],['../class_legion_1_1_mapping_1_1_mapper.html#autotoc_md45',1,'Select Sharding Functor'],['../class_legion_1_1_mapping_1_1_mapper.html#autotoc_md59',1,'Select Sharding Functor'],['../class_legion_1_1_mapping_1_1_mapper.html#autotoc_md69',1,'Select Sharding Functor'],['../class_legion_1_1_mapping_1_1_mapper.html#autotoc_md71',1,'Select Sharding Functor'],['../class_legion_1_1_mapping_1_1_mapper.html#autotoc_md51',1,'Select Sharding Functor']]],
  ['select_20steal_20targets_9',['Select Steal Targets',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_stealing_input.html#autotoc_md87',1,'']]],
  ['select_20task_20options_10',['Select Task Options',['../struct_legion_1_1_mapping_1_1_mapper_1_1_task_options.html#autotoc_md7',1,'']]],
  ['select_20task_20sources_11',['Select Task Sources',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_task_src_input.html#autotoc_md21',1,'']]],
  ['select_20task_20variant_12',['Select Task Variant',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_variant_input.html#autotoc_md17',1,'']]],
  ['select_20tasks_20to_20map_13',['Select Tasks to Map',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_mapping_input.html#autotoc_md85',1,'']]],
  ['select_20tunable_20variable_14',['Select Tunable Variable',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_tunable_input.html#autotoc_md77',1,'']]],
  ['select_5fsharding_5ffunctor_15',['select_sharding_functor',['../class_legion_1_1_mapping_1_1_mapper.html#ae893c1df0c57b42e11ba6559535e9dfb',1,'Legion::Mapping::Mapper::select_sharding_functor(MapperContext ctx, const Fill &amp;fill, const SelectShardingFunctorInput &amp;input, SelectShardingFunctorOutput &amp;output)=0'],['../class_legion_1_1_mapping_1_1_mapper.html#a00c288cd76445e37a0bc6e287e337c2b',1,'Legion::Mapping::Mapper::select_sharding_functor(MapperContext ctx, const Partition &amp;partition, const SelectShardingFunctorInput &amp;input, SelectShardingFunctorOutput &amp;output)=0'],['../class_legion_1_1_mapping_1_1_mapper.html#a7831ade79a9301d1dbaeed8555a7ac7a',1,'Legion::Mapping::Mapper::select_sharding_functor(MapperContext ctx, const Release &amp;release, const SelectShardingFunctorInput &amp;input, SelectShardingFunctorOutput &amp;output)=0'],['../class_legion_1_1_mapping_1_1_mapper.html#a2a103f34d548b8915913842d2e14b28d',1,'Legion::Mapping::Mapper::select_sharding_functor(MapperContext ctx, const Acquire &amp;acquire, const SelectShardingFunctorInput &amp;input, SelectShardingFunctorOutput &amp;output)=0'],['../class_legion_1_1_mapping_1_1_mapper.html#ac0c33a8e586c8e35cc257ef7c3fca242',1,'Legion::Mapping::Mapper::select_sharding_functor(MapperContext ctx, const Close &amp;close, const SelectShardingFunctorInput &amp;input, SelectShardingFunctorOutput &amp;output)=0'],['../class_legion_1_1_mapping_1_1_mapper.html#a1ec41cc5ae62e5be59697171ddb7a117',1,'Legion::Mapping::Mapper::select_sharding_functor(MapperContext ctx, const Copy &amp;copy, const SelectShardingFunctorInput &amp;input, SelectShardingFunctorOutput &amp;output)=0']]],
  ['select_5ftunable_5fvalue_16',['select_tunable_value',['../class_legion_1_1_runtime.html#a6d3125a143085099dcd60c99a692b5f8',1,'Legion::Runtime']]],
  ['selectclosesrcinput_17',['SelectCloseSrcInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_close_src_input.html',1,'Legion::Mapping::Mapper']]],
  ['selectclosesrcoutput_18',['SelectCloseSrcOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_close_src_output.html',1,'Legion::Mapping::Mapper']]],
  ['selectcopysrcinput_19',['SelectCopySrcInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_copy_src_input.html',1,'Legion::Mapping::Mapper']]],
  ['selectcopysrcoutput_20',['SelectCopySrcOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_copy_src_output.html',1,'Legion::Mapping::Mapper']]],
  ['selectinlinesrcinput_21',['SelectInlineSrcInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_inline_src_input.html',1,'Legion::Mapping::Mapper']]],
  ['selectinlinesrcoutput_22',['SelectInlineSrcOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_inline_src_output.html',1,'Legion::Mapping::Mapper']]],
  ['selectmappinginput_23',['SelectMappingInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_mapping_input.html',1,'Legion::Mapping::Mapper']]],
  ['selectmappingoutput_24',['SelectMappingOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_mapping_output.html',1,'Legion::Mapping::Mapper']]],
  ['selectpartitionprojectioninput_25',['SelectPartitionProjectionInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_partition_projection_input.html',1,'Legion::Mapping::Mapper']]],
  ['selectpartitionprojectionoutput_26',['SelectPartitionProjectionOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_partition_projection_output.html',1,'Legion::Mapping::Mapper']]],
  ['selectpartitionsrcinput_27',['SelectPartitionSrcInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_partition_src_input.html',1,'Legion::Mapping::Mapper']]],
  ['selectpartitionsrcoutput_28',['SelectPartitionSrcOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_partition_src_output.html',1,'Legion::Mapping::Mapper']]],
  ['selectreleasesrcinput_29',['SelectReleaseSrcInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_release_src_input.html',1,'Legion::Mapping::Mapper']]],
  ['selectreleasesrcoutput_30',['SelectReleaseSrcOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_release_src_output.html',1,'Legion::Mapping::Mapper']]],
  ['selectshardingfunctorinput_31',['SelectShardingFunctorInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_sharding_functor_input.html',1,'Legion::Mapping::Mapper']]],
  ['selectshardingfunctoroutput_32',['SelectShardingFunctorOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_sharding_functor_output.html',1,'Legion::Mapping::Mapper']]],
  ['selectstealinginput_33',['SelectStealingInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_stealing_input.html',1,'Legion::Mapping::Mapper']]],
  ['selectstealingoutput_34',['SelectStealingOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_stealing_output.html',1,'Legion::Mapping::Mapper']]],
  ['selecttasksrcinput_35',['SelectTaskSrcInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_task_src_input.html',1,'Legion::Mapping::Mapper']]],
  ['selecttasksrcoutput_36',['SelectTaskSrcOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_task_src_output.html',1,'Legion::Mapping::Mapper']]],
  ['selecttunableinput_37',['SelectTunableInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_tunable_input.html',1,'Legion::Mapping::Mapper']]],
  ['selecttunableoutput_38',['SelectTunableOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_tunable_output.html',1,'Legion::Mapping::Mapper']]],
  ['selectvariantinput_39',['SelectVariantInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_variant_input.html',1,'Legion::Mapping::Mapper']]],
  ['selectvariantoutput_40',['SelectVariantOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_variant_output.html',1,'Legion::Mapping::Mapper']]],
  ['set_5flocal_5ftask_5fvariable_5funtyped_41',['set_local_task_variable_untyped',['../class_legion_1_1_runtime.html#aa81a5d4b439a2afa8d4d9c1e25848407',1,'Legion::Runtime']]],
  ['set_5fpoint_42',['set_point',['../class_legion_1_1_argument_map.html#a08a106cfb3f8fdf066e4b61012d7d26e',1,'Legion::ArgumentMap::set_point(const DomainPoint &amp;point, const UntypedBuffer &amp;arg, bool replace=true)'],['../class_legion_1_1_argument_map.html#ac9ab54d8d8cdb8b83d557a55de260c61',1,'Legion::ArgumentMap::set_point(const DomainPoint &amp;point, const Future &amp;f, bool replace=true)']]],
  ['set_5fpoint_5farg_43',['set_point_arg',['../class_legion_1_1_argument_map.html#aad46af49418800c66833e81771c5c414',1,'Legion::ArgumentMap']]],
  ['set_5fregistration_5fcallback_44',['set_registration_callback',['../class_legion_1_1_runtime.html#af0af3c5c6d3456b11808e9f8e06c5701',1,'Legion::Runtime']]],
  ['set_5freturn_5fcode_45',['set_return_code',['../class_legion_1_1_runtime.html#a524e0c687da51d111c209e98e4aeb97c',1,'Legion::Runtime']]],
  ['set_5ftop_5flevel_5ftask_5fid_46',['set_top_level_task_id',['../class_legion_1_1_runtime.html#a63bc41e96b5b10f3435b15ef6d5f090b',1,'Legion::Runtime']]],
  ['set_5ftop_5flevel_5ftask_5fmapper_5fid_47',['set_top_level_task_mapper_id',['../class_legion_1_1_runtime.html#aa64b2a328c162ba26386019fffc5dc21',1,'Legion::Runtime']]],
  ['sharding_20functor_48',['sharding functor',['../class_legion_1_1_mapping_1_1_mapper.html#autotoc_md69',1,'Select Sharding Functor'],['../class_legion_1_1_mapping_1_1_mapper.html#autotoc_md59',1,'Select Sharding Functor'],['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_sharding_functor_input.html#autotoc_md25',1,'Select Sharding Functor'],['../class_legion_1_1_mapping_1_1_mapper.html#autotoc_md39',1,'Select Sharding Functor'],['../class_legion_1_1_mapping_1_1_mapper.html#autotoc_md51',1,'Select Sharding Functor'],['../class_legion_1_1_mapping_1_1_mapper.html#autotoc_md71',1,'Select Sharding Functor'],['../class_legion_1_1_mapping_1_1_mapper.html#autotoc_md45',1,'Select Sharding Functor'],['../struct_legion_1_1_mapping_1_1_mapper_1_1_must_epoch_sharding_functor_output.html#autotoc_md79',1,'Select Sharding Functor']]],
  ['shardingfunctor_49',['ShardingFunctor',['../class_legion_1_1_sharding_functor.html',1,'Legion']]],
  ['should_20really_20be_20called_20map_5findex_5ftask_50',['Premap Task (should really be called map_index_task)',['../struct_legion_1_1_mapping_1_1_mapper_1_1_premap_task_input.html#autotoc_md9',1,'']]],
  ['sized_20active_20messages_20on_20infiniband_20clusters_51',['medium sized active messages on Infiniband clusters.',['../class_legion_1_1_runtime.html#autotoc_md102',1,'']]],
  ['slice_20domain_52',['Slice Domain',['../struct_legion_1_1_mapping_1_1_mapper_1_1_task_slice.html#autotoc_md11',1,'']]],
  ['slicetaskinput_53',['SliceTaskInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_slice_task_input.html',1,'Legion::Mapping::Mapper']]],
  ['slicetaskoutput_54',['SliceTaskOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_slice_task_output.html',1,'Legion::Mapping::Mapper']]],
  ['sources_55',['sources',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_close_src_input.html#autotoc_md41',1,'Select Close Sources'],['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_copy_src_input.html#autotoc_md35',1,'Select Copy Sources'],['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_inline_src_input.html#autotoc_md29',1,'Select Inline Sources'],['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_partition_src_input.html#autotoc_md65',1,'Select Partition Sources'],['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_release_src_input.html#autotoc_md55',1,'Select Release Sources'],['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_task_src_input.html#autotoc_md21',1,'Select Task Sources']]],
  ['space_20within_20a_20context_56',['permitted in any field space within a context.',['../class_legion_1_1_runtime.html#autotoc_md104',1,'']]],
  ['span_57',['Span',['../class_legion_1_1_span.html',1,'Legion']]],
  ['span_3c_20ft_2c_20pm_20_3e_58',['Span&lt; FT, PM &gt;',['../class_legion_1_1_span.html',1,'Legion']]],
  ['spaniterator_59',['SpanIterator',['../class_legion_1_1_span_iterator.html',1,'Legion']]],
  ['specializedconstraint_60',['SpecializedConstraint',['../class_legion_1_1_specialized_constraint.html',1,'Legion']]],
  ['specifying_20an_20upper_20bound_20will_20not_20impact_20correctness_61',['Not specifying an upper bound will not impact correctness.',['../struct_legion_1_1_mapping_1_1_mapper_1_1_future_map_reduction_input.html#autotoc_md73',1,'']]],
  ['speculativeoutput_62',['SpeculativeOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_speculative_output.html',1,'Legion::Mapping::Mapper']]],
  ['start_63',['start',['../class_legion_1_1_runtime.html#autotoc_md100',1,'permitting the next operation to start.'],['../class_legion_1_1_runtime.html#af061eb24e7a642912907f07a2faeb823',1,'Legion::Runtime::start(int argc, char **argv, bool background=false, bool supply_default_mapper=true, bool filter=false, bool realm_initialize_network=true, bool realm_configure_machine=true)']]],
  ['start_5fprofiling_5frange_64',['start_profiling_range',['../class_legion_1_1_runtime.html#a7a615af33aa95dceccedb4f4c281db22',1,'Legion::Runtime']]],
  ['staticdependence_65',['StaticDependence',['../struct_legion_1_1_static_dependence.html',1,'Legion']]],
  ['steal_20request_66',['Permit Steal Request',['../struct_legion_1_1_mapping_1_1_mapper_1_1_steal_request_input.html#autotoc_md89',1,'']]],
  ['steal_20targets_67',['Select Steal Targets',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_stealing_input.html#autotoc_md87',1,'']]],
  ['stealing_68',['stealing',['../class_legion_1_1_runtime.html#autotoc_md97',1,'Stealing'],['../class_legion_1_1_runtime.html#autotoc_md98',1,'will never query any mapper about stealing.']]],
  ['stealrequestinput_69',['StealRequestInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_steal_request_input.html',1,'Legion::Mapping::Mapper']]],
  ['stealrequestoutput_70',['StealRequestOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_steal_request_output.html',1,'Legion::Mapping::Mapper']]],
  ['stlcomparator_71',['STLComparator',['../struct_legion_1_1_domain_point_1_1_s_t_l_comparator.html',1,'Legion::DomainPoint']]],
  ['subtract_5findex_5fspaces_72',['subtract_index_spaces',['../class_legion_1_1_runtime.html#a4cc0b0b0080a4fd9c0e88420f6efbd64',1,'Legion::Runtime']]],
  ['sumreduction_73',['SumReduction',['../class_legion_1_1_sum_reduction.html',1,'Legion']]],
  ['sumreduction_3c_20bool_20_3e_74',['SumReduction&lt; bool &gt;',['../class_legion_1_1_sum_reduction_3_01bool_01_4.html',1,'Legion']]],
  ['sumreduction_3c_20double_20_3e_75',['SumReduction&lt; double &gt;',['../class_legion_1_1_sum_reduction_3_01double_01_4.html',1,'Legion']]],
  ['sumreduction_3c_20float_20_3e_76',['SumReduction&lt; float &gt;',['../class_legion_1_1_sum_reduction_3_01float_01_4.html',1,'Legion']]],
  ['sumreduction_3c_20int16_5ft_20_3e_77',['SumReduction&lt; int16_t &gt;',['../class_legion_1_1_sum_reduction_3_01int16__t_01_4.html',1,'Legion']]],
  ['sumreduction_3c_20int32_5ft_20_3e_78',['SumReduction&lt; int32_t &gt;',['../class_legion_1_1_sum_reduction_3_01int32__t_01_4.html',1,'Legion']]],
  ['sumreduction_3c_20int64_5ft_20_3e_79',['SumReduction&lt; int64_t &gt;',['../class_legion_1_1_sum_reduction_3_01int64__t_01_4.html',1,'Legion']]],
  ['sumreduction_3c_20int8_5ft_20_3e_80',['SumReduction&lt; int8_t &gt;',['../class_legion_1_1_sum_reduction_3_01int8__t_01_4.html',1,'Legion']]],
  ['sumreduction_3c_20uint16_5ft_20_3e_81',['SumReduction&lt; uint16_t &gt;',['../class_legion_1_1_sum_reduction_3_01uint16__t_01_4.html',1,'Legion']]],
  ['sumreduction_3c_20uint32_5ft_20_3e_82',['SumReduction&lt; uint32_t &gt;',['../class_legion_1_1_sum_reduction_3_01uint32__t_01_4.html',1,'Legion']]],
  ['sumreduction_3c_20uint64_5ft_20_3e_83',['SumReduction&lt; uint64_t &gt;',['../class_legion_1_1_sum_reduction_3_01uint64__t_01_4.html',1,'Legion']]],
  ['sumreduction_3c_20uint8_5ft_20_3e_84',['SumReduction&lt; uint8_t &gt;',['../class_legion_1_1_sum_reduction_3_01uint8__t_01_4.html',1,'Legion']]],
  ['synchronization_20model_85',['Get Mapper Synchronization Model',['../class_legion_1_1_mapping_1_1_mapper.html#autotoc_md3',1,'']]]
];
