var searchData=
[
  ['enable_5fprofiling_0',['enable_profiling',['../class_legion_1_1_runtime.html#a357602aa4f54f88fe361861fa50e20a9',1,'Legion::Runtime']]],
  ['end_5fmapper_5fcall_1',['end_mapper_call',['../class_legion_1_1_runtime.html#a087efef8f6dde153b6419a591334d82d',1,'Legion::Runtime']]],
  ['end_5fstatic_5ftrace_2',['end_static_trace',['../class_legion_1_1_runtime.html#ac89bdf19645572d9fd250156aad5a383',1,'Legion::Runtime']]],
  ['end_5ftrace_3',['end_trace',['../class_legion_1_1_runtime.html#a763f3b4e9f038e43c2a79fa3419178c2',1,'Legion::Runtime']]],
  ['epoch_4',['Map Must Epoch',['../struct_legion_1_1_mapping_1_1_mapper_1_1_mapping_constraint.html#autotoc_md81',1,'']]],
  ['eqkdtreet_5',['EqKDTreeT',['../class_legion_1_1_internal_1_1_eq_k_d_tree_t.html',1,'Legion::Internal']]],
  ['error_6',['Error',['../class_legion_1_1_error.html',1,'Legion']]],
  ['exception_7',['Exception',['../class_legion_1_1_exception.html',1,'Legion']]],
  ['exceptionhandler_8',['ExceptionHandler',['../class_legion_1_1_exception_handler.html',1,'Legion']]],
  ['execute_5findex_5fspace_9',['execute_index_space',['../class_legion_1_1_runtime.html#a16abc2135ae6a97dbc1d89b1b399160d',1,'Legion::Runtime::execute_index_space(Context ctx, const IndexTaskLauncher &amp;launcher, std::vector&lt; OutputRequirement &gt; *outputs=nullptr)'],['../class_legion_1_1_runtime.html#a041162c3fe46047c46e9e00a26f75528',1,'Legion::Runtime::execute_index_space(Context ctx, TaskID task_id, const Domain domain, const std::vector&lt; IndexSpaceRequirement &gt; &amp;indexes, const std::vector&lt; FieldSpaceRequirement &gt; &amp;fields, const std::vector&lt; RegionRequirement &gt; &amp;regions, const UntypedBuffer &amp;global_arg, const ArgumentMap &amp;arg_map, ReductionOpID reduction, const UntypedBuffer &amp;initial_value, const Predicate &amp;predicate=Predicate::TRUE_PRED, bool must_parallelism=false, MapperID id=0, MappingTagID tag=0)'],['../class_legion_1_1_runtime.html#a7e5e4f0c7a374673017c11c064bae7c3',1,'Legion::Runtime::execute_index_space(Context ctx, TaskID task_id, const Domain domain, const std::vector&lt; IndexSpaceRequirement &gt; &amp;indexes, const std::vector&lt; FieldSpaceRequirement &gt; &amp;fields, const std::vector&lt; RegionRequirement &gt; &amp;regions, const UntypedBuffer &amp;global_arg, const ArgumentMap &amp;arg_map, const Predicate &amp;predicate=Predicate::TRUE_PRED, bool must_paralleism=false, MapperID id=0, MappingTagID tag=0)'],['../class_legion_1_1_runtime.html#af0c37e7f16d106b5329b91bca6afda93',1,'Legion::Runtime::execute_index_space(Context ctx, const IndexTaskLauncher &amp;launcher, ReductionOpID redop, bool ordered=true, std::vector&lt; OutputRequirement &gt; *outputs=nullptr)']]],
  ['execute_5fmust_5fepoch_10',['execute_must_epoch',['../class_legion_1_1_runtime.html#a4f219e544094fa61ddea088645482e98',1,'Legion::Runtime']]],
  ['execute_5ftask_11',['execute_task',['../class_legion_1_1_runtime.html#a632c34229db9b8cd9f4fefa68f3da57a',1,'Legion::Runtime::execute_task(Context ctx, const TaskLauncher &amp;launcher, std::vector&lt; OutputRequirement &gt; *outputs=nullptr)'],['../class_legion_1_1_runtime.html#a9a607c1fa178a6f1369b4471ec1414b0',1,'Legion::Runtime::execute_task(Context ctx, TaskID task_id, const std::vector&lt; IndexSpaceRequirement &gt; &amp;indexes, const std::vector&lt; FieldSpaceRequirement &gt; &amp;fields, const std::vector&lt; RegionRequirement &gt; &amp;regions, const UntypedBuffer &amp;arg, const Predicate &amp;predicate=Predicate::TRUE_PRED, MapperID id=0, MappingTagID tag=0)']]],
  ['execution_12',['Out-of-order Execution',['../class_legion_1_1_runtime.html#autotoc_md99',1,'']]],
  ['executionconstraintset_13',['ExecutionConstraintSet',['../class_legion_1_1_execution_constraint_set.html',1,'Legion']]],
  ['ext_5fhandoff_5fto_5flegion_14',['ext_handoff_to_legion',['../class_legion_1_1_legion_handshake.html#a8d224373d75885bdf494a9880f9a4785',1,'Legion::LegionHandshake']]],
  ['ext_5fwait_5fon_5flegion_15',['ext_wait_on_legion',['../class_legion_1_1_legion_handshake.html#abca7268a854f76995805cbfa537c147d',1,'Legion::LegionHandshake']]],
  ['externalresources_16',['ExternalResources',['../class_legion_1_1_external_resources.html',1,'Legion']]]
];
