var searchData=
[
  ['map_0',['Select Tasks to Map',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_mapping_input.html#autotoc_md85',1,'']]],
  ['map_20acquire_1',['Map Acquire',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_acquire_input.html#autotoc_md47',1,'']]],
  ['map_20copy_2',['Map Copy',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_copy_input.html#autotoc_md33',1,'']]],
  ['map_20inline_3',['Map Inline',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_inline_input.html#autotoc_md27',1,'']]],
  ['map_20must_20epoch_4',['Map Must Epoch',['../struct_legion_1_1_mapping_1_1_mapper_1_1_mapping_constraint.html#autotoc_md81',1,'']]],
  ['map_20projection_5',['Map Projection',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_partition_input.html#autotoc_md63',1,'']]],
  ['map_20release_6',['Map Release',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_release_input.html#autotoc_md53',1,'']]],
  ['map_20task_7',['Map Task',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_task_input.html#autotoc_md13',1,'']]],
  ['map_5findex_5ftask_8',['Premap Task (should really be called map_index_task)',['../struct_legion_1_1_mapping_1_1_mapper_1_1_premap_task_input.html#autotoc_md9',1,'']]],
  ['map_5fregion_9',['map_region',['../class_legion_1_1_runtime.html#a72a56d287882bf9d1b937dd9a909b409',1,'Legion::Runtime::map_region(Context ctx, const InlineLauncher &amp;launcher)'],['../class_legion_1_1_runtime.html#a083bcbdb065ce34e3fbc7d559d598cfb',1,'Legion::Runtime::map_region(Context ctx, const RegionRequirement &amp;req, MapperID id=0, MappingTagID tag=0, const char *provenance=nullptr)'],['../class_legion_1_1_runtime.html#a4dacf264336987ca6aa338fcf135876b',1,'Legion::Runtime::map_region(Context ctx, unsigned idx, MapperID id=0, MappingTagID tag=0, const char *provenance=nullptr)']]],
  ['mapacquireinput_10',['MapAcquireInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_acquire_input.html',1,'Legion::Mapping::Mapper']]],
  ['mapacquireoutput_11',['MapAcquireOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_acquire_output.html',1,'Legion::Mapping::Mapper']]],
  ['mapcloseinput_12',['MapCloseInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_close_input.html',1,'Legion::Mapping::Mapper']]],
  ['mapcloseoutput_13',['MapCloseOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_close_output.html',1,'Legion::Mapping::Mapper']]],
  ['mapcopyinput_14',['MapCopyInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_copy_input.html',1,'Legion::Mapping::Mapper']]],
  ['mapcopyoutput_15',['MapCopyOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_copy_output.html',1,'Legion::Mapping::Mapper']]],
  ['mapdataflowgraphinput_16',['MapDataflowGraphInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_dataflow_graph_input.html',1,'Legion::Mapping::Mapper']]],
  ['mapdataflowgraphoutput_17',['MapDataflowGraphOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_dataflow_graph_output.html',1,'Legion::Mapping::Mapper']]],
  ['mapinlineinput_18',['MapInlineInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_inline_input.html',1,'Legion::Mapping::Mapper']]],
  ['mapinlineoutput_19',['MapInlineOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_inline_output.html',1,'Legion::Mapping::Mapper']]],
  ['mapmustepochinput_20',['MapMustEpochInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_must_epoch_input.html',1,'Legion::Mapping::Mapper']]],
  ['mapmustepochoutput_21',['MapMustEpochOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_must_epoch_output.html',1,'Legion::Mapping::Mapper']]],
  ['mappable_22',['Mappable',['../class_legion_1_1_mappable.html',1,'Legion']]],
  ['mappartitioninput_23',['MapPartitionInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_partition_input.html',1,'Legion::Mapping::Mapper']]],
  ['mappartitionoutput_24',['MapPartitionOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_partition_output.html',1,'Legion::Mapping::Mapper']]],
  ['mapper_25',['Mapper',['../class_legion_1_1_mapping_1_1_mapper.html',1,'Legion::Mapping']]],
  ['mapper_20about_20stealing_26',['will never query any mapper about stealing.',['../class_legion_1_1_runtime.html#autotoc_md98',1,'']]],
  ['mapper_20name_27',['Get Mapper Name',['../class_legion_1_1_mapping_1_1_mapper.html#autotoc_md1',1,'']]],
  ['mapper_20synchronization_20model_28',['Get Mapper Synchronization Model',['../class_legion_1_1_mapping_1_1_mapper.html#autotoc_md3',1,'']]],
  ['mapperevent_29',['MapperEvent',['../class_legion_1_1_mapping_1_1_mapper_event.html',1,'Legion::Mapping']]],
  ['mappermessage_30',['MapperMessage',['../struct_legion_1_1_mapping_1_1_mapper_1_1_mapper_message.html',1,'Legion::Mapping::Mapper']]],
  ['mapperruntime_31',['MapperRuntime',['../class_legion_1_1_mapping_1_1_mapper_runtime.html',1,'Legion::Mapping']]],
  ['mappersyncmodel_32',['MapperSyncModel',['../class_legion_1_1_mapping_1_1_mapper.html#aac6137b73db2aade62938c3dd206322a',1,'Legion::Mapping::Mapper']]],
  ['mappertaskresult_33',['MapperTaskResult',['../struct_legion_1_1_mapping_1_1_mapper_1_1_mapper_task_result.html',1,'Legion::Mapping::Mapper']]],
  ['mappingconstraint_34',['MappingConstraint',['../struct_legion_1_1_mapping_1_1_mapper_1_1_mapping_constraint.html',1,'Legion::Mapping::Mapper']]],
  ['mapreleaseinput_35',['MapReleaseInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_release_input.html',1,'Legion::Mapping::Mapper']]],
  ['mapreleaseoutput_36',['MapReleaseOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_release_output.html',1,'Legion::Mapping::Mapper']]],
  ['mapreplicatetaskoutput_37',['MapReplicateTaskOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_replicate_task_output.html',1,'Legion::Mapping::Mapper']]],
  ['maptaskinput_38',['MapTaskInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_task_input.html',1,'Legion::Mapping::Mapper']]],
  ['maptaskoutput_39',['MapTaskOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_task_output.html',1,'Legion::Mapping::Mapper']]],
  ['maxreduction_40',['MaxReduction',['../class_legion_1_1_max_reduction.html',1,'Legion']]],
  ['maxreduction_3c_20bool_20_3e_41',['MaxReduction&lt; bool &gt;',['../class_legion_1_1_max_reduction_3_01bool_01_4.html',1,'Legion']]],
  ['maxreduction_3c_20double_20_3e_42',['MaxReduction&lt; double &gt;',['../class_legion_1_1_max_reduction_3_01double_01_4.html',1,'Legion']]],
  ['maxreduction_3c_20float_20_3e_43',['MaxReduction&lt; float &gt;',['../class_legion_1_1_max_reduction_3_01float_01_4.html',1,'Legion']]],
  ['maxreduction_3c_20int16_5ft_20_3e_44',['MaxReduction&lt; int16_t &gt;',['../class_legion_1_1_max_reduction_3_01int16__t_01_4.html',1,'Legion']]],
  ['maxreduction_3c_20int32_5ft_20_3e_45',['MaxReduction&lt; int32_t &gt;',['../class_legion_1_1_max_reduction_3_01int32__t_01_4.html',1,'Legion']]],
  ['maxreduction_3c_20int64_5ft_20_3e_46',['MaxReduction&lt; int64_t &gt;',['../class_legion_1_1_max_reduction_3_01int64__t_01_4.html',1,'Legion']]],
  ['maxreduction_3c_20int8_5ft_20_3e_47',['MaxReduction&lt; int8_t &gt;',['../class_legion_1_1_max_reduction_3_01int8__t_01_4.html',1,'Legion']]],
  ['maxreduction_3c_20uint16_5ft_20_3e_48',['MaxReduction&lt; uint16_t &gt;',['../class_legion_1_1_max_reduction_3_01uint16__t_01_4.html',1,'Legion']]],
  ['maxreduction_3c_20uint32_5ft_20_3e_49',['MaxReduction&lt; uint32_t &gt;',['../class_legion_1_1_max_reduction_3_01uint32__t_01_4.html',1,'Legion']]],
  ['maxreduction_3c_20uint64_5ft_20_3e_50',['MaxReduction&lt; uint64_t &gt;',['../class_legion_1_1_max_reduction_3_01uint64__t_01_4.html',1,'Legion']]],
  ['maxreduction_3c_20uint8_5ft_20_3e_51',['MaxReduction&lt; uint8_t &gt;',['../class_legion_1_1_max_reduction_3_01uint8__t_01_4.html',1,'Legion']]],
  ['medium_20sized_20active_20messages_20on_20infiniband_20clusters_52',['medium sized active messages on Infiniband clusters.',['../class_legion_1_1_runtime.html#autotoc_md102',1,'']]],
  ['memoizable_53',['Memoizable',['../class_legion_1_1_internal_1_1_memoizable.html',1,'Legion::Internal']]],
  ['memoize_20operation_54',['Memoize Operation',['../struct_legion_1_1_mapping_1_1_mapper_1_1_memoize_input.html#autotoc_md83',1,'']]],
  ['memoizeinput_55',['MemoizeInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_memoize_input.html',1,'Legion::Mapping::Mapper']]],
  ['memoizeoutput_56',['MemoizeOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_memoize_output.html',1,'Legion::Mapping::Mapper']]],
  ['memoryconstraint_57',['MemoryConstraint',['../class_legion_1_1_memory_constraint.html',1,'Legion']]],
  ['message_58',['Handle Message',['../struct_legion_1_1_mapping_1_1_mapper_1_1_mapper_message.html#autotoc_md91',1,'']]],
  ['messages_20on_20infiniband_20clusters_59',['medium sized active messages on Infiniband clusters.',['../class_legion_1_1_runtime.html#autotoc_md102',1,'']]],
  ['messaging_60',['Messaging',['../class_legion_1_1_runtime.html#autotoc_md101',1,'']]],
  ['minreduction_61',['MinReduction',['../class_legion_1_1_min_reduction.html',1,'Legion']]],
  ['minreduction_3c_20bool_20_3e_62',['MinReduction&lt; bool &gt;',['../class_legion_1_1_min_reduction_3_01bool_01_4.html',1,'Legion']]],
  ['minreduction_3c_20double_20_3e_63',['MinReduction&lt; double &gt;',['../class_legion_1_1_min_reduction_3_01double_01_4.html',1,'Legion']]],
  ['minreduction_3c_20float_20_3e_64',['MinReduction&lt; float &gt;',['../class_legion_1_1_min_reduction_3_01float_01_4.html',1,'Legion']]],
  ['minreduction_3c_20int16_5ft_20_3e_65',['MinReduction&lt; int16_t &gt;',['../class_legion_1_1_min_reduction_3_01int16__t_01_4.html',1,'Legion']]],
  ['minreduction_3c_20int32_5ft_20_3e_66',['MinReduction&lt; int32_t &gt;',['../class_legion_1_1_min_reduction_3_01int32__t_01_4.html',1,'Legion']]],
  ['minreduction_3c_20int64_5ft_20_3e_67',['MinReduction&lt; int64_t &gt;',['../class_legion_1_1_min_reduction_3_01int64__t_01_4.html',1,'Legion']]],
  ['minreduction_3c_20int8_5ft_20_3e_68',['MinReduction&lt; int8_t &gt;',['../class_legion_1_1_min_reduction_3_01int8__t_01_4.html',1,'Legion']]],
  ['minreduction_3c_20uint16_5ft_20_3e_69',['MinReduction&lt; uint16_t &gt;',['../class_legion_1_1_min_reduction_3_01uint16__t_01_4.html',1,'Legion']]],
  ['minreduction_3c_20uint32_5ft_20_3e_70',['MinReduction&lt; uint32_t &gt;',['../class_legion_1_1_min_reduction_3_01uint32__t_01_4.html',1,'Legion']]],
  ['minreduction_3c_20uint64_5ft_20_3e_71',['MinReduction&lt; uint64_t &gt;',['../class_legion_1_1_min_reduction_3_01uint64__t_01_4.html',1,'Legion']]],
  ['minreduction_3c_20uint8_5ft_20_3e_72',['MinReduction&lt; uint8_t &gt;',['../class_legion_1_1_min_reduction_3_01uint8__t_01_4.html',1,'Legion']]],
  ['model_73',['Get Mapper Synchronization Model',['../class_legion_1_1_mapping_1_1_mapper.html#autotoc_md3',1,'']]],
  ['more_20nodes_20prior_20to_20an_20application_20beginning_74',['one or more nodes prior to an application beginning.',['../class_legion_1_1_runtime.html#autotoc_md110',1,'']]],
  ['mpi_5fhandoff_5fto_5flegion_75',['mpi_handoff_to_legion',['../class_legion_1_1_m_p_i_legion_handshake.html#a31dc62d5ef169915a806c792d1cd3d19',1,'Legion::MPILegionHandshake']]],
  ['mpi_5fwait_5fon_5flegion_76',['mpi_wait_on_legion',['../class_legion_1_1_m_p_i_legion_handshake.html#a8b364a1ccade595e3dc3753ac272bb20',1,'Legion::MPILegionHandshake']]],
  ['mpilegionhandshake_77',['MPILegionHandshake',['../class_legion_1_1_m_p_i_legion_handshake.html',1,'Legion']]],
  ['must_20epoch_78',['Map Must Epoch',['../struct_legion_1_1_mapping_1_1_mapper_1_1_mapping_constraint.html#autotoc_md81',1,'']]],
  ['mustepoch_79',['MustEpoch',['../class_legion_1_1_must_epoch.html',1,'Legion']]],
  ['mustepochlauncher_80',['MustEpochLauncher',['../struct_legion_1_1_must_epoch_launcher.html',1,'Legion']]],
  ['mustepochshardingfunctoroutput_81',['MustEpochShardingFunctorOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_must_epoch_sharding_functor_output.html',1,'Legion::Mapping::Mapper']]]
];
