var searchData=
[
  ['launch_5ftop_5flevel_5ftask_0',['launch_top_level_task',['../class_legion_1_1_runtime.html#a97b45946044f7672c734111a4960d4c2',1,'Legion::Runtime']]],
  ['launchconstraint_1',['LaunchConstraint',['../class_legion_1_1_launch_constraint.html',1,'Legion']]],
  ['layoutconstraint_2',['LayoutConstraint',['../class_legion_1_1_layout_constraint.html',1,'Legion']]],
  ['layoutconstraintregistrar_3',['LayoutConstraintRegistrar',['../struct_legion_1_1_layout_constraint_registrar.html',1,'Legion']]],
  ['layoutconstraintset_4',['LayoutConstraintSet',['../class_legion_1_1_layout_constraint_set.html',1,'Legion']]],
  ['legion_20runtime_20documentation_5',['Legion Runtime Documentation',['../index.html',1,'']]],
  ['legion_2eh_6',['legion.h',['../legion_8h.html',1,'']]],
  ['legion_5fbyte_5foffset_5ft_7',['legion_byte_offset_t',['../structlegion__byte__offset__t.html',1,'']]],
  ['legion_5fdomain_5faffine_5ftransform_5ft_8',['legion_domain_affine_transform_t',['../structlegion__domain__affine__transform__t.html',1,'']]],
  ['legion_5fdomain_5fpoint_5ft_9',['legion_domain_point_t',['../structlegion__domain__point__t.html',1,'']]],
  ['legion_5fdomain_5ft_10',['legion_domain_t',['../structlegion__domain__t.html',1,'']]],
  ['legion_5fdomain_5ftransform_5ft_11',['legion_domain_transform_t',['../structlegion__domain__transform__t.html',1,'']]],
  ['legion_5fdynamic_5fcollective_5ft_12',['legion_dynamic_collective_t',['../structlegion__dynamic__collective__t.html',1,'']]],
  ['legion_5ffield_5fspace_5ft_13',['legion_field_space_t',['../structlegion__field__space__t.html',1,'']]],
  ['legion_5fhandoff_5fto_5fext_14',['legion_handoff_to_ext',['../class_legion_1_1_legion_handshake.html#a044b3b59a7c0e899686c3d3f8d25ad27',1,'Legion::LegionHandshake']]],
  ['legion_5fhandoff_5fto_5fmpi_15',['legion_handoff_to_mpi',['../class_legion_1_1_m_p_i_legion_handshake.html#a2bd8bb781f5c182ab999ad7e8dfdf19e',1,'Legion::MPILegionHandshake']]],
  ['legion_5findex_5fpartition_5ft_16',['legion_index_partition_t',['../structlegion__index__partition__t.html',1,'']]],
  ['legion_5findex_5fspace_5ft_17',['legion_index_space_t',['../structlegion__index__space__t.html',1,'']]],
  ['legion_5finput_5fargs_5ft_18',['legion_input_args_t',['../structlegion__input__args__t.html',1,'']]],
  ['legion_5flogical_5fpartition_5ft_19',['legion_logical_partition_t',['../structlegion__logical__partition__t.html',1,'']]],
  ['legion_5flogical_5fregion_5ft_20',['legion_logical_region_t',['../structlegion__logical__region__t.html',1,'']]],
  ['legion_5fmemory_5ft_21',['legion_memory_t',['../structlegion__memory__t.html',1,'']]],
  ['legion_5fphase_5fbarrier_5ft_22',['legion_phase_barrier_t',['../structlegion__phase__barrier__t.html',1,'']]],
  ['legion_5fprocessor_5ft_23',['legion_processor_t',['../structlegion__processor__t.html',1,'']]],
  ['legion_5fptr_5ft_24',['legion_ptr_t',['../structlegion__ptr__t.html',1,'']]],
  ['legion_5fslice_5ftask_5finput_5ft_25',['legion_slice_task_input_t',['../structlegion__slice__task__input__t.html',1,'']]],
  ['legion_5ftask_5fconfig_5foptions_5ft_26',['legion_task_config_options_t',['../structlegion__task__config__options__t.html',1,'']]],
  ['legion_5ftask_5foptions_5ft_27',['legion_task_options_t',['../structlegion__task__options__t.html',1,'']]],
  ['legion_5ftask_5fpostamble_28',['legion_task_postamble',['../class_legion_1_1_runtime.html#af0137b0a6a8055887a2a1c6232230345',1,'Legion::Runtime::legion_task_postamble(Context ctx, const Domain &amp;domain, bool take_ownership, const void *metadataptr=nullptr, size_t metadatasize=0)'],['../class_legion_1_1_runtime.html#a98e8a94e27a29be6628f23730e25e786',1,'Legion::Runtime::legion_task_postamble(Context ctx, FutureFunctor *callback_functor, bool owned=false)'],['../class_legion_1_1_runtime.html#a3e152658fbe81fb705ecc59712643380',1,'Legion::Runtime::legion_task_postamble(Context ctx, const void *retvalptr, size_t retvalsize, bool owned, const Realm::ExternalInstanceResource &amp;allocation, void(*freefunc)(const Realm::ExternalInstanceResource &amp;)=nullptr, const void *metadataptr=nullptr, size_t metadatasize=0)'],['../class_legion_1_1_runtime.html#a70163426035a00e0013ec7fbdadf2335',1,'Legion::Runtime::legion_task_postamble(Context ctx, const void *retvalptr=nullptr, size_t retvalsize=0, bool owned=false, Realm::RegionInstance inst=Realm::RegionInstance::NO_INST, const void *metadataptr=nullptr, size_t metadatasize=0)']]],
  ['legion_5ftask_5fpreamble_29',['legion_task_preamble',['../class_legion_1_1_runtime.html#a75cae296df9a998053907a268f907c9e',1,'Legion::Runtime']]],
  ['legion_5ftask_5fslice_5ft_30',['legion_task_slice_t',['../structlegion__task__slice__t.html',1,'']]],
  ['legion_5funtyped_5fbuffer_5ft_31',['legion_untyped_buffer_t',['../structlegion__untyped__buffer__t.html',1,'']]],
  ['legion_5fwait_5fon_5fext_32',['legion_wait_on_ext',['../class_legion_1_1_legion_handshake.html#a9385f6927b0ee75c68dc266423f345a1',1,'Legion::LegionHandshake']]],
  ['legion_5fwait_5fon_5fmpi_33',['legion_wait_on_mpi',['../class_legion_1_1_m_p_i_legion_handshake.html#a5e8bf4cb8ab74eedff58086309b896b3',1,'Legion::MPILegionHandshake']]],
  ['legionhandshake_34',['LegionHandshake',['../class_legion_1_1_legion_handshake.html',1,'Legion']]],
  ['lgevent_35',['LgEvent',['../class_legion_1_1_internal_1_1_lg_event.html',1,'Legion::Internal']]],
  ['list_36',['Deprecated List',['../deprecated.html',1,'']]],
  ['locallock_37',['LocalLock',['../class_legion_1_1_internal_1_1_local_lock.html',1,'Legion::Internal']]],
  ['lock_38',['Lock',['../class_legion_1_1_lock.html',1,'Legion']]],
  ['lockrequest_39',['LockRequest',['../struct_legion_1_1_lock_request.html',1,'Legion']]],
  ['log_5fonce_40',['log_once',['../class_legion_1_1_runtime.html#a71eda2e1e351ddb779295fd6d6313edd',1,'Legion::Runtime']]],
  ['logicalpartition_41',['LogicalPartition',['../class_legion_1_1_logical_partition.html',1,'Legion']]],
  ['logicalpartitiont_42',['LogicalPartitionT',['../class_legion_1_1_logical_partition_t.html',1,'Legion']]],
  ['logicalregion_43',['LogicalRegion',['../class_legion_1_1_logical_region.html',1,'Legion']]],
  ['logicalregiont_44',['LogicalRegionT',['../class_legion_1_1_logical_region_t.html',1,'Legion']]]
];
