var searchData=
[
  ['tag_0',['tag',['../struct_legion_1_1_region_requirement.html#a99daa01e4bb69154391412b5951ac11c',1,'Legion::RegionRequirement']]],
  ['targets_1',['Select Steal Targets',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_stealing_input.html#autotoc_md87',1,'']]],
  ['task_2',['task',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_task_input.html#autotoc_md13',1,'Map Task'],['../struct_legion_1_1_mapping_1_1_mapper_1_1_post_map_input.html#autotoc_md19',1,'Postmap Task'],['../struct_legion_1_1_mapping_1_1_mapper_1_1_replicate_task_input.html#autotoc_md15',1,'Replicate Task'],['../class_legion_1_1_task.html',1,'Legion::Task'],['../class_legion_1_1_mapping_1_1_shim_mapper_1_1_task.html',1,'Legion::Mapping::ShimMapper::Task']]],
  ['task_20options_3',['Select Task Options',['../struct_legion_1_1_mapping_1_1_mapper_1_1_task_options.html#autotoc_md7',1,'']]],
  ['task_20result_4',['Handle Task Result',['../struct_legion_1_1_mapping_1_1_mapper_1_1_mapper_task_result.html#autotoc_md93',1,'']]],
  ['task_20should_20really_20be_20called_20map_5findex_5ftask_5',['Premap Task (should really be called map_index_task)',['../struct_legion_1_1_mapping_1_1_mapper_1_1_premap_task_input.html#autotoc_md9',1,'']]],
  ['task_20sources_6',['Select Task Sources',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_task_src_input.html#autotoc_md21',1,'']]],
  ['task_20variant_7',['Select Task Variant',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_variant_input.html#autotoc_md17',1,'']]],
  ['taskconfigoptions_8',['TaskConfigOptions',['../struct_legion_1_1_task_config_options.html',1,'Legion']]],
  ['taskgeneratorarguments_9',['TaskGeneratorArguments',['../struct_legion_1_1_mapping_1_1_task_generator_arguments.html',1,'Legion::Mapping']]],
  ['tasklauncher_10',['TaskLauncher',['../struct_legion_1_1_task_launcher.html',1,'Legion']]],
  ['tasklayoutconstraintset_11',['TaskLayoutConstraintSet',['../class_legion_1_1_task_layout_constraint_set.html',1,'Legion']]],
  ['taskmappinginfo_12',['TaskMappingInfo',['../struct_legion_1_1_mapping_1_1_replay_mapper_1_1_task_mapping_info.html',1,'Legion::Mapping::ReplayMapper']]],
  ['taskoptions_13',['TaskOptions',['../struct_legion_1_1_mapping_1_1_mapper_1_1_task_options.html',1,'Legion::Mapping::Mapper']]],
  ['taskprofilinginfo_14',['TaskProfilingInfo',['../struct_legion_1_1_mapping_1_1_mapper_1_1_task_profiling_info.html',1,'Legion::Mapping::Mapper']]],
  ['tasks_20to_20map_15',['Select Tasks to Map',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_mapping_input.html#autotoc_md85',1,'']]],
  ['taskslice_16',['TaskSlice',['../struct_legion_1_1_mapping_1_1_mapper_1_1_task_slice.html',1,'Legion::Mapping::Mapper']]],
  ['taskvariantcollection_17',['TaskVariantCollection',['../class_legion_1_1_mapping_1_1_shim_mapper_1_1_task_variant_collection.html',1,'Legion::Mapping::ShimMapper']]],
  ['taskvariantregistrar_18',['TaskVariantRegistrar',['../struct_legion_1_1_task_variant_registrar.html',1,'Legion']]],
  ['test_5fmapper_2eh_19',['test_mapper.h',['../test__mapper_8h.html',1,'']]],
  ['testmapper_20',['TestMapper',['../class_legion_1_1_mapping_1_1_test_mapper.html',1,'Legion::Mapping']]],
  ['that_20is_20performed_20on_20captured_20traces_21',['optimization that is performed on captured traces',['../class_legion_1_1_runtime.html#autotoc_md106',1,'']]],
  ['the_20next_20operation_20to_20start_22',['permitting the next operation to start.',['../class_legion_1_1_runtime.html#autotoc_md100',1,'']]],
  ['the_20next_20two_20flags_23',['operations commit using the next two flags.',['../class_legion_1_1_runtime.html#autotoc_md108',1,'']]],
  ['tilingconstraint_24',['TilingConstraint',['../class_legion_1_1_tiling_constraint.html',1,'Legion']]],
  ['timinglauncher_25',['TimingLauncher',['../struct_legion_1_1_timing_launcher.html',1,'Legion']]],
  ['to_20an_20application_20beginning_26',['one or more nodes prior to an application beginning.',['../class_legion_1_1_runtime.html#autotoc_md110',1,'']]],
  ['to_20map_27',['Select Tasks to Map',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_mapping_input.html#autotoc_md85',1,'']]],
  ['to_20start_28',['permitting the next operation to start.',['../class_legion_1_1_runtime.html#autotoc_md100',1,'']]],
  ['to_5fstring_29',['to_string',['../mapping__utilities_8h.html#a0896c5dee1850ae808c81ca8a2bf9af9',1,'Legion::Mapping::Utilities']]],
  ['traces_30',['optimization that is performed on captured traces',['../class_legion_1_1_runtime.html#autotoc_md106',1,'']]],
  ['tracing_31',['Tracing',['../class_legion_1_1_runtime.html#autotoc_md105',1,'']]],
  ['transform_5ffuture_5fmap_32',['transform_future_map',['../class_legion_1_1_runtime.html#acd7f67cb91ca30bbfb5eb802ea4cca5f',1,'Legion::Runtime']]],
  ['transforms_2eh_33',['transforms.h',['../transforms_8h.html',1,'']]],
  ['tunable_20variable_34',['Select Tunable Variable',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_tunable_input.html#autotoc_md77',1,'']]],
  ['tunablelauncher_35',['TunableLauncher',['../struct_legion_1_1_tunable_launcher.html',1,'Legion']]],
  ['tunablemapping_36',['TunableMapping',['../struct_legion_1_1_mapping_1_1_replay_mapper_1_1_tunable_mapping.html',1,'Legion::Mapping::ReplayMapper']]],
  ['two_20flags_37',['operations commit using the next two flags.',['../class_legion_1_1_runtime.html#autotoc_md108',1,'']]],
  ['types_2eh_38',['types.h',['../types_8h.html',1,'']]]
];
