var searchData=
[
  ['machinequeryinterface_0',['MachineQueryInterface',['../class_legion_1_1_mapping_1_1_utilities_1_1_machine_query_interface.html',1,'Legion::Mapping::Utilities']]],
  ['map_1',['Select Tasks to Map',['../struct_legion_1_1_mapping_1_1_mapper_1_1_select_mapping_input.html#autotoc_md85',1,'']]],
  ['map_20acquire_2',['Map Acquire',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_acquire_input.html#autotoc_md47',1,'']]],
  ['map_20copy_3',['Map Copy',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_copy_input.html#autotoc_md33',1,'']]],
  ['map_20inline_4',['Map Inline',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_inline_input.html#autotoc_md27',1,'']]],
  ['map_20must_20epoch_5',['Map Must Epoch',['../struct_legion_1_1_mapping_1_1_mapper_1_1_mapping_constraint.html#autotoc_md81',1,'']]],
  ['map_20projection_6',['Map Projection',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_partition_input.html#autotoc_md63',1,'']]],
  ['map_20release_7',['Map Release',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_release_input.html#autotoc_md53',1,'']]],
  ['map_20task_8',['Map Task',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_task_input.html#autotoc_md13',1,'']]],
  ['map_5findex_5ftask_9',['Premap Task (should really be called map_index_task)',['../struct_legion_1_1_mapping_1_1_mapper_1_1_premap_task_input.html#autotoc_md9',1,'']]],
  ['map_5fregion_10',['map_region',['../class_legion_1_1_runtime.html#a72a56d287882bf9d1b937dd9a909b409',1,'Legion::Runtime::map_region(Context ctx, const InlineLauncher &amp;launcher)'],['../class_legion_1_1_runtime.html#a083bcbdb065ce34e3fbc7d559d598cfb',1,'Legion::Runtime::map_region(Context ctx, const RegionRequirement &amp;req, MapperID id=0, MappingTagID tag=0, const char *provenance=nullptr)'],['../class_legion_1_1_runtime.html#a4dacf264336987ca6aa338fcf135876b',1,'Legion::Runtime::map_region(Context ctx, unsigned idx, MapperID id=0, MappingTagID tag=0, const char *provenance=nullptr)']]],
  ['mapacquireinput_11',['MapAcquireInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_acquire_input.html',1,'Legion::Mapping::Mapper']]],
  ['mapacquireoutput_12',['MapAcquireOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_acquire_output.html',1,'Legion::Mapping::Mapper']]],
  ['mapcloseinput_13',['MapCloseInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_close_input.html',1,'Legion::Mapping::Mapper']]],
  ['mapcloseoutput_14',['MapCloseOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_close_output.html',1,'Legion::Mapping::Mapper']]],
  ['mapcopyinput_15',['MapCopyInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_copy_input.html',1,'Legion::Mapping::Mapper']]],
  ['mapcopyoutput_16',['MapCopyOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_copy_output.html',1,'Legion::Mapping::Mapper']]],
  ['mapdataflowgraphinput_17',['MapDataflowGraphInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_dataflow_graph_input.html',1,'Legion::Mapping::Mapper']]],
  ['mapdataflowgraphoutput_18',['MapDataflowGraphOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_dataflow_graph_output.html',1,'Legion::Mapping::Mapper']]],
  ['mapinlineinput_19',['MapInlineInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_inline_input.html',1,'Legion::Mapping::Mapper']]],
  ['mapinlineoutput_20',['MapInlineOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_inline_output.html',1,'Legion::Mapping::Mapper']]],
  ['mapmustepochinput_21',['MapMustEpochInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_must_epoch_input.html',1,'Legion::Mapping::Mapper']]],
  ['mapmustepochoutput_22',['MapMustEpochOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_must_epoch_output.html',1,'Legion::Mapping::Mapper']]],
  ['mappable_23',['mappable',['../class_legion_1_1_mappable.html',1,'Legion::Mappable'],['../class_legion_1_1_mapping_1_1_shim_mapper_1_1_mappable.html',1,'Legion::Mapping::ShimMapper::Mappable']]],
  ['mappartitioninput_24',['MapPartitionInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_partition_input.html',1,'Legion::Mapping::Mapper']]],
  ['mappartitionoutput_25',['MapPartitionOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_partition_output.html',1,'Legion::Mapping::Mapper']]],
  ['mapper_26',['Mapper',['../class_legion_1_1_mapping_1_1_mapper.html',1,'Legion::Mapping']]],
  ['mapper_20about_20stealing_27',['will never query any mapper about stealing.',['../class_legion_1_1_runtime.html#autotoc_md98',1,'']]],
  ['mapper_20name_28',['Get Mapper Name',['../class_legion_1_1_mapping_1_1_wrapper_mapper.html#autotoc_md1',1,'']]],
  ['mapper_20synchronization_20model_29',['Get Mapper Synchronization Model',['../class_legion_1_1_mapping_1_1_mapper.html#autotoc_md3',1,'']]],
  ['mapperevent_30',['MapperEvent',['../class_legion_1_1_mapping_1_1_mapper_event.html',1,'Legion::Mapping']]],
  ['mappermessage_31',['MapperMessage',['../struct_legion_1_1_mapping_1_1_mapper_1_1_mapper_message.html',1,'Legion::Mapping::Mapper']]],
  ['mappermsghdr_32',['MapperMsgHdr',['../struct_legion_1_1_mapping_1_1_default_mapper_1_1_mapper_msg_hdr.html',1,'Legion::Mapping::DefaultMapper']]],
  ['mapperruntime_33',['MapperRuntime',['../class_legion_1_1_mapping_1_1_mapper_runtime.html',1,'Legion::Mapping']]],
  ['mappersyncmodel_34',['MapperSyncModel',['../class_legion_1_1_mapping_1_1_mapper.html#aac6137b73db2aade62938c3dd206322a',1,'Legion::Mapping::Mapper']]],
  ['mappertaskresult_35',['MapperTaskResult',['../struct_legion_1_1_mapping_1_1_mapper_1_1_mapper_task_result.html',1,'Legion::Mapping::Mapper']]],
  ['mapping_2eh_36',['mapping.h',['../mapping_8h.html',1,'']]],
  ['mapping_5futilities_2eh_37',['mapping_utilities.h',['../mapping__utilities_8h.html',1,'']]],
  ['mappingconstraint_38',['MappingConstraint',['../struct_legion_1_1_mapping_1_1_mapper_1_1_mapping_constraint.html',1,'Legion::Mapping::Mapper']]],
  ['mappingmemoizer_39',['MappingMemoizer',['../class_legion_1_1_mapping_1_1_utilities_1_1_mapping_memoizer.html',1,'Legion::Mapping::Utilities']]],
  ['mappingprofiler_40',['MappingProfiler',['../class_legion_1_1_mapping_1_1_utilities_1_1_mapping_profiler.html',1,'Legion::Mapping::Utilities']]],
  ['mapreleaseinput_41',['MapReleaseInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_release_input.html',1,'Legion::Mapping::Mapper']]],
  ['mapreleaseoutput_42',['MapReleaseOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_release_output.html',1,'Legion::Mapping::Mapper']]],
  ['mapreplicatetaskoutput_43',['MapReplicateTaskOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_replicate_task_output.html',1,'Legion::Mapping::Mapper']]],
  ['maptaskinput_44',['MapTaskInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_task_input.html',1,'Legion::Mapping::Mapper']]],
  ['maptaskoutput_45',['MapTaskOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_map_task_output.html',1,'Legion::Mapping::Mapper']]],
  ['maxreduction_46',['MaxReduction',['../class_legion_1_1_max_reduction.html',1,'Legion']]],
  ['maxreduction_3c_20bool_20_3e_47',['MaxReduction&lt; bool &gt;',['../class_legion_1_1_max_reduction_3_01bool_01_4.html',1,'Legion']]],
  ['maxreduction_3c_20double_20_3e_48',['MaxReduction&lt; double &gt;',['../class_legion_1_1_max_reduction_3_01double_01_4.html',1,'Legion']]],
  ['maxreduction_3c_20float_20_3e_49',['MaxReduction&lt; float &gt;',['../class_legion_1_1_max_reduction_3_01float_01_4.html',1,'Legion']]],
  ['maxreduction_3c_20int16_5ft_20_3e_50',['MaxReduction&lt; int16_t &gt;',['../class_legion_1_1_max_reduction_3_01int16__t_01_4.html',1,'Legion']]],
  ['maxreduction_3c_20int32_5ft_20_3e_51',['MaxReduction&lt; int32_t &gt;',['../class_legion_1_1_max_reduction_3_01int32__t_01_4.html',1,'Legion']]],
  ['maxreduction_3c_20int64_5ft_20_3e_52',['MaxReduction&lt; int64_t &gt;',['../class_legion_1_1_max_reduction_3_01int64__t_01_4.html',1,'Legion']]],
  ['maxreduction_3c_20int8_5ft_20_3e_53',['MaxReduction&lt; int8_t &gt;',['../class_legion_1_1_max_reduction_3_01int8__t_01_4.html',1,'Legion']]],
  ['maxreduction_3c_20uint16_5ft_20_3e_54',['MaxReduction&lt; uint16_t &gt;',['../class_legion_1_1_max_reduction_3_01uint16__t_01_4.html',1,'Legion']]],
  ['maxreduction_3c_20uint32_5ft_20_3e_55',['MaxReduction&lt; uint32_t &gt;',['../class_legion_1_1_max_reduction_3_01uint32__t_01_4.html',1,'Legion']]],
  ['maxreduction_3c_20uint64_5ft_20_3e_56',['MaxReduction&lt; uint64_t &gt;',['../class_legion_1_1_max_reduction_3_01uint64__t_01_4.html',1,'Legion']]],
  ['maxreduction_3c_20uint8_5ft_20_3e_57',['MaxReduction&lt; uint8_t &gt;',['../class_legion_1_1_max_reduction_3_01uint8__t_01_4.html',1,'Legion']]],
  ['medium_20sized_20active_20messages_20on_20infiniband_20clusters_58',['medium sized active messages on Infiniband clusters.',['../class_legion_1_1_runtime.html#autotoc_md102',1,'']]],
  ['memoizable_59',['Memoizable',['../class_legion_1_1_internal_1_1_memoizable.html',1,'Legion::Internal']]],
  ['memoize_20operation_60',['Memoize Operation',['../struct_legion_1_1_mapping_1_1_mapper_1_1_memoize_input.html#autotoc_md83',1,'']]],
  ['memoizedmapping_61',['MemoizedMapping',['../struct_legion_1_1_mapping_1_1_utilities_1_1_mapping_memoizer_1_1_memoized_mapping.html',1,'Legion::Mapping::Utilities::MappingMemoizer']]],
  ['memoizeinput_62',['MemoizeInput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_memoize_input.html',1,'Legion::Mapping::Mapper']]],
  ['memoizeoutput_63',['MemoizeOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_memoize_output.html',1,'Legion::Mapping::Mapper']]],
  ['memoryconstraint_64',['MemoryConstraint',['../class_legion_1_1_memory_constraint.html',1,'Legion']]],
  ['message_65',['Handle Message',['../struct_legion_1_1_mapping_1_1_mapper_1_1_mapper_message.html#autotoc_md91',1,'']]],
  ['messages_20on_20infiniband_20clusters_66',['medium sized active messages on Infiniband clusters.',['../class_legion_1_1_runtime.html#autotoc_md102',1,'']]],
  ['messaging_67',['Messaging',['../class_legion_1_1_runtime.html#autotoc_md101',1,'']]],
  ['minreduction_68',['MinReduction',['../class_legion_1_1_min_reduction.html',1,'Legion']]],
  ['minreduction_3c_20bool_20_3e_69',['MinReduction&lt; bool &gt;',['../class_legion_1_1_min_reduction_3_01bool_01_4.html',1,'Legion']]],
  ['minreduction_3c_20double_20_3e_70',['MinReduction&lt; double &gt;',['../class_legion_1_1_min_reduction_3_01double_01_4.html',1,'Legion']]],
  ['minreduction_3c_20float_20_3e_71',['MinReduction&lt; float &gt;',['../class_legion_1_1_min_reduction_3_01float_01_4.html',1,'Legion']]],
  ['minreduction_3c_20int16_5ft_20_3e_72',['MinReduction&lt; int16_t &gt;',['../class_legion_1_1_min_reduction_3_01int16__t_01_4.html',1,'Legion']]],
  ['minreduction_3c_20int32_5ft_20_3e_73',['MinReduction&lt; int32_t &gt;',['../class_legion_1_1_min_reduction_3_01int32__t_01_4.html',1,'Legion']]],
  ['minreduction_3c_20int64_5ft_20_3e_74',['MinReduction&lt; int64_t &gt;',['../class_legion_1_1_min_reduction_3_01int64__t_01_4.html',1,'Legion']]],
  ['minreduction_3c_20int8_5ft_20_3e_75',['MinReduction&lt; int8_t &gt;',['../class_legion_1_1_min_reduction_3_01int8__t_01_4.html',1,'Legion']]],
  ['minreduction_3c_20uint16_5ft_20_3e_76',['MinReduction&lt; uint16_t &gt;',['../class_legion_1_1_min_reduction_3_01uint16__t_01_4.html',1,'Legion']]],
  ['minreduction_3c_20uint32_5ft_20_3e_77',['MinReduction&lt; uint32_t &gt;',['../class_legion_1_1_min_reduction_3_01uint32__t_01_4.html',1,'Legion']]],
  ['minreduction_3c_20uint64_5ft_20_3e_78',['MinReduction&lt; uint64_t &gt;',['../class_legion_1_1_min_reduction_3_01uint64__t_01_4.html',1,'Legion']]],
  ['minreduction_3c_20uint8_5ft_20_3e_79',['MinReduction&lt; uint8_t &gt;',['../class_legion_1_1_min_reduction_3_01uint8__t_01_4.html',1,'Legion']]],
  ['model_80',['Get Mapper Synchronization Model',['../class_legion_1_1_mapping_1_1_mapper.html#autotoc_md3',1,'']]],
  ['more_20nodes_20prior_20to_20an_20application_20beginning_81',['one or more nodes prior to an application beginning.',['../class_legion_1_1_runtime.html#autotoc_md110',1,'']]],
  ['mpi_5fhandoff_5fto_5flegion_82',['mpi_handoff_to_legion',['../class_legion_1_1_m_p_i_legion_handshake.html#a31dc62d5ef169915a806c792d1cd3d19',1,'Legion::MPILegionHandshake']]],
  ['mpi_5fwait_5fon_5flegion_83',['mpi_wait_on_legion',['../class_legion_1_1_m_p_i_legion_handshake.html#a8b364a1ccade595e3dc3753ac272bb20',1,'Legion::MPILegionHandshake']]],
  ['mpilegionhandshake_84',['MPILegionHandshake',['../class_legion_1_1_m_p_i_legion_handshake.html',1,'Legion']]],
  ['must_20epoch_85',['Map Must Epoch',['../struct_legion_1_1_mapping_1_1_mapper_1_1_mapping_constraint.html#autotoc_md81',1,'']]],
  ['mustepoch_86',['MustEpoch',['../class_legion_1_1_must_epoch.html',1,'Legion']]],
  ['mustepochlauncher_87',['MustEpochLauncher',['../struct_legion_1_1_must_epoch_launcher.html',1,'Legion']]],
  ['mustepochshardingfunctoroutput_88',['MustEpochShardingFunctorOutput',['../struct_legion_1_1_mapping_1_1_mapper_1_1_must_epoch_sharding_functor_output.html',1,'Legion::Mapping::Mapper']]]
];
