var searchData=
[
  ['task_0',['task',['../class_legion_1_1_task.html',1,'Legion::Task'],['../class_legion_1_1_mapping_1_1_shim_mapper_1_1_task.html',1,'Legion::Mapping::ShimMapper::Task']]],
  ['taskconfigoptions_1',['TaskConfigOptions',['../struct_legion_1_1_task_config_options.html',1,'Legion']]],
  ['taskgeneratorarguments_2',['TaskGeneratorArguments',['../struct_legion_1_1_mapping_1_1_task_generator_arguments.html',1,'Legion::Mapping']]],
  ['tasklauncher_3',['TaskLauncher',['../struct_legion_1_1_task_launcher.html',1,'Legion']]],
  ['tasklayoutconstraintset_4',['TaskLayoutConstraintSet',['../class_legion_1_1_task_layout_constraint_set.html',1,'Legion']]],
  ['taskmappinginfo_5',['TaskMappingInfo',['../struct_legion_1_1_mapping_1_1_replay_mapper_1_1_task_mapping_info.html',1,'Legion::Mapping::ReplayMapper']]],
  ['taskoptions_6',['TaskOptions',['../struct_legion_1_1_mapping_1_1_mapper_1_1_task_options.html',1,'Legion::Mapping::Mapper']]],
  ['taskprofilinginfo_7',['TaskProfilingInfo',['../struct_legion_1_1_mapping_1_1_mapper_1_1_task_profiling_info.html',1,'Legion::Mapping::Mapper']]],
  ['taskslice_8',['TaskSlice',['../struct_legion_1_1_mapping_1_1_mapper_1_1_task_slice.html',1,'Legion::Mapping::Mapper']]],
  ['taskvariantcollection_9',['TaskVariantCollection',['../class_legion_1_1_mapping_1_1_shim_mapper_1_1_task_variant_collection.html',1,'Legion::Mapping::ShimMapper']]],
  ['taskvariantregistrar_10',['TaskVariantRegistrar',['../struct_legion_1_1_task_variant_registrar.html',1,'Legion']]],
  ['testmapper_11',['TestMapper',['../class_legion_1_1_mapping_1_1_test_mapper.html',1,'Legion::Mapping']]],
  ['tilingconstraint_12',['TilingConstraint',['../class_legion_1_1_tiling_constraint.html',1,'Legion']]],
  ['timinglauncher_13',['TimingLauncher',['../struct_legion_1_1_timing_launcher.html',1,'Legion']]],
  ['tunablelauncher_14',['TunableLauncher',['../struct_legion_1_1_tunable_launcher.html',1,'Legion']]],
  ['tunablemapping_15',['TunableMapping',['../struct_legion_1_1_mapping_1_1_replay_mapper_1_1_tunable_mapping.html',1,'Legion::Mapping::ReplayMapper']]]
];
