var hierarchy =
[
    [ "Legion::ArraySyntax::AccessorRefHelper< typename, PrivilegeMode >", "class_legion_1_1_array_syntax_1_1_accessor_ref_helper.html", null ],
    [ "Legion::AcquireLauncher", "struct_legion_1_1_acquire_launcher.html", null ],
    [ "Legion::Mapping::Mapper::AcquireProfilingInfo", "struct_legion_1_1_mapping_1_1_mapper_1_1_acquire_profiling_info.html", null ],
    [ "Legion::ArraySyntax::AffineRefHelper< typename >", "class_legion_1_1_array_syntax_1_1_affine_ref_helper.html", null ],
    [ "Legion::AffineTransform< M, N, T >", "struct_legion_1_1_affine_transform.html", null ],
    [ "Legion::Internal::AllGatherCollective< bool >", "class_legion_1_1_internal_1_1_all_gather_collective.html", null ],
    [ "Legion::Internal::AllReduceCollective< T, bool >", "class_legion_1_1_internal_1_1_all_reduce_collective.html", null ],
    [ "Legion::AndReduction< T >", "class_legion_1_1_and_reduction.html", null ],
    [ "Legion::AndReduction< int16_t >", "class_legion_1_1_and_reduction_3_01int16__t_01_4.html", null ],
    [ "Legion::AndReduction< int32_t >", "class_legion_1_1_and_reduction_3_01int32__t_01_4.html", null ],
    [ "Legion::AndReduction< int64_t >", "class_legion_1_1_and_reduction_3_01int64__t_01_4.html", null ],
    [ "Legion::AndReduction< int8_t >", "class_legion_1_1_and_reduction_3_01int8__t_01_4.html", null ],
    [ "Legion::AndReduction< uint16_t >", "class_legion_1_1_and_reduction_3_01uint16__t_01_4.html", null ],
    [ "Legion::AndReduction< uint32_t >", "class_legion_1_1_and_reduction_3_01uint32__t_01_4.html", null ],
    [ "Legion::AndReduction< uint64_t >", "class_legion_1_1_and_reduction_3_01uint64__t_01_4.html", null ],
    [ "Legion::AndReduction< uint8_t >", "class_legion_1_1_and_reduction_3_01uint8__t_01_4.html", null ],
    [ "Legion::AttachLauncher", "struct_legion_1_1_attach_launcher.html", null ],
    [ "Legion::Internal::AutoLock", "class_legion_1_1_internal_1_1_auto_lock.html", [
      [ "Legion::Internal::AutoTryLock", "class_legion_1_1_internal_1_1_auto_try_lock.html", null ],
      [ "Legion::Mapping::AutoLock", "class_legion_1_1_mapping_1_1_auto_lock.html", null ]
    ] ],
    [ "Legion::Internal::BarrierExchangeCollective< T >", "class_legion_1_1_internal_1_1_barrier_exchange_collective.html", null ],
    [ "Legion::Mapping::DefaultMapper::CachedTaskMapping", "struct_legion_1_1_mapping_1_1_default_mapper_1_1_cached_task_mapping.html", null ],
    [ "Legion::Mapping::ReplayMapper::CloseMappingInfo", "struct_legion_1_1_mapping_1_1_replay_mapper_1_1_close_mapping_info.html", null ],
    [ "Legion::Mapping::Mapper::CloseProfilingInfo", "struct_legion_1_1_mapping_1_1_mapper_1_1_close_profiling_info.html", null ],
    [ "Collective", "class_collective.html", null ],
    [ "Legion::Mapping::CollectiveView", "class_legion_1_1_mapping_1_1_collective_view.html", null ],
    [ "Legion::ColocationConstraint", "class_legion_1_1_colocation_constraint.html", null ],
    [ "Legion::Internal::ColorSpaceLinearizationT< DIM, T >", "class_legion_1_1_internal_1_1_color_space_linearization_t.html", null ],
    [ "Legion::ConcurrentColoringFunctor", "class_legion_1_1_concurrent_coloring_functor.html", null ],
    [ "Legion::Mapping::Mapper::ContextConfigOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_context_config_output.html", null ],
    [ "Legion::CopyLauncher", "struct_legion_1_1_copy_launcher.html", null ],
    [ "Legion::Mapping::ReplayMapper::CopyMappingInfo", "struct_legion_1_1_mapping_1_1_replay_mapper_1_1_copy_mapping_info.html", null ],
    [ "Legion::Mapping::Mapper::CopyProfilingInfo", "struct_legion_1_1_mapping_1_1_mapper_1_1_copy_profiling_info.html", null ],
    [ "Legion::Mapping::Mapper::CreateCloseTemporaryInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_create_close_temporary_input.html", null ],
    [ "Legion::Mapping::Mapper::CreateCloseTemporaryOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_create_close_temporary_output.html", null ],
    [ "Legion::Mapping::Mapper::CreateCopyTemporaryInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_create_copy_temporary_input.html", null ],
    [ "Legion::Mapping::Mapper::CreateCopyTemporaryOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_create_copy_temporary_output.html", null ],
    [ "Legion::Mapping::Mapper::CreateInlineTemporaryInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_create_inline_temporary_input.html", null ],
    [ "Legion::Mapping::Mapper::CreateInlineTemporaryOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_create_inline_temporary_output.html", null ],
    [ "Legion::Mapping::Mapper::CreatePartitionTemporaryInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_create_partition_temporary_input.html", null ],
    [ "Legion::Mapping::Mapper::CreatePartitionTemporaryOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_create_partition_temporary_output.html", null ],
    [ "Legion::Mapping::Mapper::CreateReleaseTemporaryInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_create_release_temporary_input.html", null ],
    [ "Legion::Mapping::Mapper::CreateReleaseTemporaryOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_create_release_temporary_output.html", null ],
    [ "Legion::Mapping::Mapper::CreateTaskTemporaryInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_create_task_temporary_input.html", null ],
    [ "Legion::Mapping::Mapper::CreateTaskTemporaryOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_create_task_temporary_output.html", null ],
    [ "Legion::DeferredBufferRequest", "struct_legion_1_1_deferred_buffer_request.html", null ],
    [ "Legion::DeferredValueRequest", "struct_legion_1_1_deferred_value_request.html", null ],
    [ "Legion::DiffReduction< T >", "class_legion_1_1_diff_reduction.html", null ],
    [ "Legion::DiffReduction< double >", "class_legion_1_1_diff_reduction_3_01double_01_4.html", null ],
    [ "Legion::DiffReduction< float >", "class_legion_1_1_diff_reduction_3_01float_01_4.html", null ],
    [ "Legion::DiffReduction< int16_t >", "class_legion_1_1_diff_reduction_3_01int16__t_01_4.html", null ],
    [ "Legion::DiffReduction< int32_t >", "class_legion_1_1_diff_reduction_3_01int32__t_01_4.html", null ],
    [ "Legion::DiffReduction< int64_t >", "class_legion_1_1_diff_reduction_3_01int64__t_01_4.html", null ],
    [ "Legion::DiffReduction< int8_t >", "class_legion_1_1_diff_reduction_3_01int8__t_01_4.html", null ],
    [ "Legion::DiffReduction< uint16_t >", "class_legion_1_1_diff_reduction_3_01uint16__t_01_4.html", null ],
    [ "Legion::DiffReduction< uint32_t >", "class_legion_1_1_diff_reduction_3_01uint32__t_01_4.html", null ],
    [ "Legion::DiffReduction< uint64_t >", "class_legion_1_1_diff_reduction_3_01uint64__t_01_4.html", null ],
    [ "Legion::DiffReduction< uint8_t >", "class_legion_1_1_diff_reduction_3_01uint8__t_01_4.html", null ],
    [ "Legion::Internal::NT_TemplateHelper::DimHelper", "struct_legion_1_1_internal_1_1_n_t___template_helper_1_1_dim_helper.html", null ],
    [ "Legion::DiscardLauncher", "struct_legion_1_1_discard_launcher.html", null ],
    [ "Legion::DivReduction< T >", "class_legion_1_1_div_reduction.html", null ],
    [ "Legion::DivReduction< double >", "class_legion_1_1_div_reduction_3_01double_01_4.html", null ],
    [ "Legion::DivReduction< float >", "class_legion_1_1_div_reduction_3_01float_01_4.html", null ],
    [ "Legion::DivReduction< int16_t >", "class_legion_1_1_div_reduction_3_01int16__t_01_4.html", null ],
    [ "Legion::DivReduction< int32_t >", "class_legion_1_1_div_reduction_3_01int32__t_01_4.html", null ],
    [ "Legion::DivReduction< int64_t >", "class_legion_1_1_div_reduction_3_01int64__t_01_4.html", null ],
    [ "Legion::DivReduction< int8_t >", "class_legion_1_1_div_reduction_3_01int8__t_01_4.html", null ],
    [ "Legion::DivReduction< uint16_t >", "class_legion_1_1_div_reduction_3_01uint16__t_01_4.html", null ],
    [ "Legion::DivReduction< uint32_t >", "class_legion_1_1_div_reduction_3_01uint32__t_01_4.html", null ],
    [ "Legion::DivReduction< uint64_t >", "class_legion_1_1_div_reduction_3_01uint64__t_01_4.html", null ],
    [ "Legion::DivReduction< uint8_t >", "class_legion_1_1_div_reduction_3_01uint8__t_01_4.html", null ],
    [ "Legion::Domain", "class_legion_1_1_domain.html", null ],
    [ "Legion::DomainAffineTransform", "class_legion_1_1_domain_affine_transform.html", null ],
    [ "Legion::DomainPoint", "class_legion_1_1_domain_point.html", null ],
    [ "Legion::Domain::DomainPointIterator", "class_legion_1_1_domain_1_1_domain_point_iterator.html", null ],
    [ "Legion::DomainScaleTransform", "class_legion_1_1_domain_scale_transform.html", null ],
    [ "Legion::DomainTransform", "class_legion_1_1_domain_transform.html", null ],
    [ "Legion::Internal::EqKDTreeT< DIM, T >", "class_legion_1_1_internal_1_1_eq_k_d_tree_t.html", null ],
    [ "Legion::Error", "class_legion_1_1_error.html", null ],
    [ "Realm::Event", null, [
      [ "Legion::Internal::LgEvent", "class_legion_1_1_internal_1_1_lg_event.html", [
        [ "Legion::Internal::ApEvent", "class_legion_1_1_internal_1_1_ap_event.html", [
          [ "Legion::Internal::ApBarrier", "class_legion_1_1_internal_1_1_ap_barrier.html", null ],
          [ "Legion::Internal::ApUserEvent", "class_legion_1_1_internal_1_1_ap_user_event.html", null ]
        ] ],
        [ "Legion::Internal::PredEvent", "class_legion_1_1_internal_1_1_pred_event.html", [
          [ "Legion::Internal::PredUserEvent", "class_legion_1_1_internal_1_1_pred_user_event.html", null ]
        ] ],
        [ "Legion::Internal::RtEvent", "class_legion_1_1_internal_1_1_rt_event.html", [
          [ "Legion::Internal::RtBarrier", "class_legion_1_1_internal_1_1_rt_barrier.html", null ],
          [ "Legion::Internal::RtUserEvent", "class_legion_1_1_internal_1_1_rt_user_event.html", null ]
        ] ]
      ] ]
    ] ],
    [ "Legion::ExceptionHandler", "class_legion_1_1_exception_handler.html", null ],
    [ "Legion::ExecutionConstraintSet", "class_legion_1_1_execution_constraint_set.html", null ],
    [ "Legion::Fatal", "class_legion_1_1_fatal.html", null ],
    [ "Legion::FieldAccessor< MODE, FT, N, COORD_T, A, CHECK_BOUNDS >", "class_legion_1_1_field_accessor.html", null ],
    [ "Legion::FieldSpace", "class_legion_1_1_field_space.html", null ],
    [ "Legion::FieldSpaceRequirement", "struct_legion_1_1_field_space_requirement.html", null ],
    [ "Legion::FillLauncher", "struct_legion_1_1_fill_launcher.html", null ],
    [ "Legion::FutureFunctor", "class_legion_1_1_future_functor.html", null ],
    [ "Legion::Mapping::Mapper::FutureMapReductionInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_future_map_reduction_input.html", null ],
    [ "Legion::Mapping::Mapper::FutureMapReductionOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_future_map_reduction_output.html", null ],
    [ "Legion::Grant", "class_legion_1_1_grant.html", null ],
    [ "Legion::IndexAttachLauncher", "struct_legion_1_1_index_attach_launcher.html", null ],
    [ "Legion::IndexCopyLauncher", "struct_legion_1_1_index_copy_launcher.html", null ],
    [ "Legion::IndexFillLauncher", "struct_legion_1_1_index_fill_launcher.html", null ],
    [ "Legion::IndexPartition", "class_legion_1_1_index_partition.html", [
      [ "Legion::IndexPartitionT< DIM, COORD_T >", "class_legion_1_1_index_partition_t.html", null ]
    ] ],
    [ "Legion::Internal::IndexPartNodeT< DIM, T >", "class_legion_1_1_internal_1_1_index_part_node_t.html", null ],
    [ "Legion::IndexSpace", "class_legion_1_1_index_space.html", [
      [ "Legion::IndexSpaceT< DIM, COORD_T >", "class_legion_1_1_index_space_t.html", null ]
    ] ],
    [ "Legion::Internal::IndexSpaceDifference< DIM, T >", "class_legion_1_1_internal_1_1_index_space_difference.html", null ],
    [ "Legion::Internal::IndexSpaceIntersection< DIM, T >", "class_legion_1_1_internal_1_1_index_space_intersection.html", null ],
    [ "Legion::Internal::IndexSpaceNodeT< DIM, T >", "class_legion_1_1_internal_1_1_index_space_node_t.html", null ],
    [ "Legion::Internal::IndexSpaceOperationT< DIM, T >", "class_legion_1_1_internal_1_1_index_space_operation_t.html", null ],
    [ "Legion::IndexSpaceRequirement", "struct_legion_1_1_index_space_requirement.html", null ],
    [ "Legion::Internal::IndexSpaceUnion< DIM, T >", "class_legion_1_1_internal_1_1_index_space_union.html", null ],
    [ "Legion::IndexTaskLauncher", "struct_legion_1_1_index_task_launcher.html", null ],
    [ "Legion::InlineLauncher", "struct_legion_1_1_inline_launcher.html", null ],
    [ "Legion::Mapping::ReplayMapper::InlineMappingInfo", "struct_legion_1_1_mapping_1_1_replay_mapper_1_1_inline_mapping_info.html", null ],
    [ "Legion::Mapping::Mapper::InlineProfilingInfo", "struct_legion_1_1_mapping_1_1_mapper_1_1_inline_profiling_info.html", null ],
    [ "Legion::InputArgs", "struct_legion_1_1_input_args.html", null ],
    [ "Legion::Mapping::ReplayMapper::InstanceInfo", "struct_legion_1_1_mapping_1_1_replay_mapper_1_1_instance_info.html", null ],
    [ "Legion::ISAConstraint", "class_legion_1_1_i_s_a_constraint.html", null ],
    [ "Legion::Span< FT, PM >::iterator", "class_legion_1_1_span_1_1iterator.html", null ],
    [ "Legion::Internal::KDNode< DIM, T, RT >", "class_legion_1_1_internal_1_1_k_d_node.html", null ],
    [ "Legion::LaunchConstraint", "class_legion_1_1_launch_constraint.html", null ],
    [ "Legion::LayoutConstraint", "class_legion_1_1_layout_constraint.html", [
      [ "Legion::AlignmentConstraint", "class_legion_1_1_alignment_constraint.html", null ],
      [ "Legion::DimensionConstraint", "class_legion_1_1_dimension_constraint.html", null ],
      [ "Legion::FieldConstraint", "class_legion_1_1_field_constraint.html", null ],
      [ "Legion::MemoryConstraint", "class_legion_1_1_memory_constraint.html", null ],
      [ "Legion::OffsetConstraint", "class_legion_1_1_offset_constraint.html", null ],
      [ "Legion::OrderingConstraint", "class_legion_1_1_ordering_constraint.html", null ],
      [ "Legion::PaddingConstraint", "class_legion_1_1_padding_constraint.html", null ],
      [ "Legion::PointerConstraint", "class_legion_1_1_pointer_constraint.html", null ],
      [ "Legion::SpecializedConstraint", "class_legion_1_1_specialized_constraint.html", null ],
      [ "Legion::TilingConstraint", "class_legion_1_1_tiling_constraint.html", null ]
    ] ],
    [ "Legion::LayoutConstraintRegistrar", "struct_legion_1_1_layout_constraint_registrar.html", null ],
    [ "Legion::LayoutConstraintSet", "class_legion_1_1_layout_constraint_set.html", null ],
    [ "legion_byte_offset_t", "structlegion__byte__offset__t.html", null ],
    [ "legion_domain_affine_transform_t", "structlegion__domain__affine__transform__t.html", null ],
    [ "legion_domain_point_t", "structlegion__domain__point__t.html", null ],
    [ "legion_domain_t", "structlegion__domain__t.html", null ],
    [ "legion_domain_transform_t", "structlegion__domain__transform__t.html", null ],
    [ "legion_dynamic_collective_t", "structlegion__dynamic__collective__t.html", null ],
    [ "legion_field_space_t", "structlegion__field__space__t.html", null ],
    [ "legion_index_partition_t", "structlegion__index__partition__t.html", null ],
    [ "legion_index_space_t", "structlegion__index__space__t.html", null ],
    [ "legion_input_args_t", "structlegion__input__args__t.html", null ],
    [ "legion_logical_partition_t", "structlegion__logical__partition__t.html", null ],
    [ "legion_logical_region_t", "structlegion__logical__region__t.html", null ],
    [ "legion_memory_t", "structlegion__memory__t.html", null ],
    [ "legion_phase_barrier_t", "structlegion__phase__barrier__t.html", null ],
    [ "legion_processor_t", "structlegion__processor__t.html", null ],
    [ "legion_ptr_t", "structlegion__ptr__t.html", null ],
    [ "legion_slice_task_input_t", "structlegion__slice__task__input__t.html", null ],
    [ "legion_task_config_options_t", "structlegion__task__config__options__t.html", null ],
    [ "legion_task_options_t", "structlegion__task__options__t.html", null ],
    [ "legion_task_slice_t", "structlegion__task__slice__t.html", null ],
    [ "legion_untyped_buffer_t", "structlegion__untyped__buffer__t.html", null ],
    [ "Realm::DynamicTemplates::ListProduct2", null, [
      [ "Legion::Internal::NT_TemplateHelper", "struct_legion_1_1_internal_1_1_n_t___template_helper.html", null ]
    ] ],
    [ "Legion::Internal::LocalLock", "class_legion_1_1_internal_1_1_local_lock.html", null ],
    [ "Legion::Lock", "class_legion_1_1_lock.html", null ],
    [ "Legion::LockRequest", "struct_legion_1_1_lock_request.html", null ],
    [ "Legion::LogicalPartition", "class_legion_1_1_logical_partition.html", [
      [ "Legion::LogicalPartitionT< DIM, COORD_T >", "class_legion_1_1_logical_partition_t.html", null ]
    ] ],
    [ "Legion::LogicalRegion", "class_legion_1_1_logical_region.html", [
      [ "Legion::LogicalRegionT< DIM, COORD_T >", "class_legion_1_1_logical_region_t.html", null ]
    ] ],
    [ "Legion::Mapping::Utilities::MachineQueryInterface", "class_legion_1_1_mapping_1_1_utilities_1_1_machine_query_interface.html", null ],
    [ "Legion::Mapping::Mapper::MapAcquireInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_map_acquire_input.html", null ],
    [ "Legion::Mapping::Mapper::MapAcquireOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_map_acquire_output.html", null ],
    [ "Legion::Mapping::Mapper::MapCloseInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_map_close_input.html", null ],
    [ "Legion::Mapping::Mapper::MapCloseOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_map_close_output.html", null ],
    [ "Legion::Mapping::Mapper::MapCopyInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_map_copy_input.html", null ],
    [ "Legion::Mapping::Mapper::MapCopyOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_map_copy_output.html", null ],
    [ "Legion::Mapping::Mapper::MapDataflowGraphInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_map_dataflow_graph_input.html", null ],
    [ "Legion::Mapping::Mapper::MapDataflowGraphOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_map_dataflow_graph_output.html", null ],
    [ "Legion::Mapping::Mapper::MapInlineInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_map_inline_input.html", null ],
    [ "Legion::Mapping::Mapper::MapInlineOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_map_inline_output.html", null ],
    [ "Legion::Mapping::Mapper::MapMustEpochInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_map_must_epoch_input.html", null ],
    [ "Legion::Mapping::Mapper::MapMustEpochOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_map_must_epoch_output.html", null ],
    [ "Legion::Mappable", "class_legion_1_1_mappable.html", [
      [ "Legion::Acquire", "class_legion_1_1_acquire.html", null ],
      [ "Legion::Close", "class_legion_1_1_close.html", null ],
      [ "Legion::Copy", "class_legion_1_1_copy.html", [
        [ "Legion::Mapping::ShimMapper::Copy", "class_legion_1_1_mapping_1_1_shim_mapper_1_1_copy.html", null ]
      ] ],
      [ "Legion::Fill", "class_legion_1_1_fill.html", null ],
      [ "Legion::InlineMapping", "class_legion_1_1_inline_mapping.html", [
        [ "Legion::Mapping::ShimMapper::Inline", "class_legion_1_1_mapping_1_1_shim_mapper_1_1_inline.html", null ]
      ] ],
      [ "Legion::MustEpoch", "class_legion_1_1_must_epoch.html", null ],
      [ "Legion::Partition", "class_legion_1_1_partition.html", null ],
      [ "Legion::Release", "class_legion_1_1_release.html", null ],
      [ "Legion::Task", "class_legion_1_1_task.html", [
        [ "Legion::Mapping::ShimMapper::Task", "class_legion_1_1_mapping_1_1_shim_mapper_1_1_task.html", null ]
      ] ]
    ] ],
    [ "Legion::Mapping::ShimMapper::Mappable", "class_legion_1_1_mapping_1_1_shim_mapper_1_1_mappable.html", [
      [ "Legion::Mapping::ShimMapper::Copy", "class_legion_1_1_mapping_1_1_shim_mapper_1_1_copy.html", null ],
      [ "Legion::Mapping::ShimMapper::Inline", "class_legion_1_1_mapping_1_1_shim_mapper_1_1_inline.html", null ],
      [ "Legion::Mapping::ShimMapper::Task", "class_legion_1_1_mapping_1_1_shim_mapper_1_1_task.html", null ]
    ] ],
    [ "Legion::Mapping::Mapper::MapPartitionInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_map_partition_input.html", null ],
    [ "Legion::Mapping::Mapper::MapPartitionOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_map_partition_output.html", null ],
    [ "Legion::Mapping::Mapper", "class_legion_1_1_mapping_1_1_mapper.html", [
      [ "Legion::Mapping::DefaultMapper", "class_legion_1_1_mapping_1_1_default_mapper.html", [
        [ "Legion::Mapping::ShimMapper", "class_legion_1_1_mapping_1_1_shim_mapper.html", null ],
        [ "Legion::Mapping::TestMapper", "class_legion_1_1_mapping_1_1_test_mapper.html", null ]
      ] ],
      [ "Legion::Mapping::ForwardingMapper", "class_legion_1_1_mapping_1_1_forwarding_mapper.html", [
        [ "Legion::Mapping::LoggingWrapper", "class_legion_1_1_mapping_1_1_logging_wrapper.html", null ]
      ] ],
      [ "Legion::Mapping::NullMapper", "class_legion_1_1_mapping_1_1_null_mapper.html", null ],
      [ "Legion::Mapping::ReplayMapper", "class_legion_1_1_mapping_1_1_replay_mapper.html", [
        [ "Legion::Mapping::DebugMapper", "class_legion_1_1_mapping_1_1_debug_mapper.html", null ]
      ] ],
      [ "Legion::Mapping::WrapperMapper", "class_legion_1_1_mapping_1_1_wrapper_mapper.html", null ]
    ] ],
    [ "Legion::Mapping::MapperEvent", "class_legion_1_1_mapping_1_1_mapper_event.html", null ],
    [ "Legion::Mapping::Mapper::MapperMessage", "struct_legion_1_1_mapping_1_1_mapper_1_1_mapper_message.html", null ],
    [ "Legion::Mapping::DefaultMapper::MapperMsgHdr", "struct_legion_1_1_mapping_1_1_default_mapper_1_1_mapper_msg_hdr.html", [
      [ "Legion::Mapping::DefaultMapper::ProfilingSampleMsg", "struct_legion_1_1_mapping_1_1_default_mapper_1_1_profiling_sample_msg.html", null ]
    ] ],
    [ "Legion::Mapping::MapperRuntime", "class_legion_1_1_mapping_1_1_mapper_runtime.html", null ],
    [ "Legion::Mapping::Mapper::MapperTaskResult", "struct_legion_1_1_mapping_1_1_mapper_1_1_mapper_task_result.html", null ],
    [ "Legion::Mapping::Mapper::MappingConstraint", "struct_legion_1_1_mapping_1_1_mapper_1_1_mapping_constraint.html", null ],
    [ "Legion::Mapping::Utilities::MappingMemoizer", "class_legion_1_1_mapping_1_1_utilities_1_1_mapping_memoizer.html", null ],
    [ "Legion::Mapping::Utilities::MappingProfiler", "class_legion_1_1_mapping_1_1_utilities_1_1_mapping_profiler.html", null ],
    [ "Legion::Mapping::Mapper::MapReleaseInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_map_release_input.html", null ],
    [ "Legion::Mapping::Mapper::MapReleaseOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_map_release_output.html", null ],
    [ "Legion::Mapping::Mapper::MapReplicateTaskOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_map_replicate_task_output.html", null ],
    [ "Legion::Mapping::Mapper::MapTaskInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_map_task_input.html", null ],
    [ "Legion::Mapping::Mapper::MapTaskOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_map_task_output.html", null ],
    [ "Legion::MaxReduction< T >", "class_legion_1_1_max_reduction.html", null ],
    [ "Legion::MaxReduction< bool >", "class_legion_1_1_max_reduction_3_01bool_01_4.html", null ],
    [ "Legion::MaxReduction< double >", "class_legion_1_1_max_reduction_3_01double_01_4.html", null ],
    [ "Legion::MaxReduction< float >", "class_legion_1_1_max_reduction_3_01float_01_4.html", null ],
    [ "Legion::MaxReduction< int16_t >", "class_legion_1_1_max_reduction_3_01int16__t_01_4.html", null ],
    [ "Legion::MaxReduction< int32_t >", "class_legion_1_1_max_reduction_3_01int32__t_01_4.html", null ],
    [ "Legion::MaxReduction< int64_t >", "class_legion_1_1_max_reduction_3_01int64__t_01_4.html", null ],
    [ "Legion::MaxReduction< int8_t >", "class_legion_1_1_max_reduction_3_01int8__t_01_4.html", null ],
    [ "Legion::MaxReduction< uint16_t >", "class_legion_1_1_max_reduction_3_01uint16__t_01_4.html", null ],
    [ "Legion::MaxReduction< uint32_t >", "class_legion_1_1_max_reduction_3_01uint32__t_01_4.html", null ],
    [ "Legion::MaxReduction< uint64_t >", "class_legion_1_1_max_reduction_3_01uint64__t_01_4.html", null ],
    [ "Legion::MaxReduction< uint8_t >", "class_legion_1_1_max_reduction_3_01uint8__t_01_4.html", null ],
    [ "Legion::Internal::Memoizable< OP >", "class_legion_1_1_internal_1_1_memoizable.html", null ],
    [ "Legion::Mapping::Utilities::MappingMemoizer::MemoizedMapping", "struct_legion_1_1_mapping_1_1_utilities_1_1_mapping_memoizer_1_1_memoized_mapping.html", null ],
    [ "Legion::Mapping::Mapper::MemoizeInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_memoize_input.html", null ],
    [ "Legion::Mapping::Mapper::MemoizeOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_memoize_output.html", null ],
    [ "Legion::MinReduction< T >", "class_legion_1_1_min_reduction.html", null ],
    [ "Legion::MinReduction< bool >", "class_legion_1_1_min_reduction_3_01bool_01_4.html", null ],
    [ "Legion::MinReduction< double >", "class_legion_1_1_min_reduction_3_01double_01_4.html", null ],
    [ "Legion::MinReduction< float >", "class_legion_1_1_min_reduction_3_01float_01_4.html", null ],
    [ "Legion::MinReduction< int16_t >", "class_legion_1_1_min_reduction_3_01int16__t_01_4.html", null ],
    [ "Legion::MinReduction< int32_t >", "class_legion_1_1_min_reduction_3_01int32__t_01_4.html", null ],
    [ "Legion::MinReduction< int64_t >", "class_legion_1_1_min_reduction_3_01int64__t_01_4.html", null ],
    [ "Legion::MinReduction< int8_t >", "class_legion_1_1_min_reduction_3_01int8__t_01_4.html", null ],
    [ "Legion::MinReduction< uint16_t >", "class_legion_1_1_min_reduction_3_01uint16__t_01_4.html", null ],
    [ "Legion::MinReduction< uint32_t >", "class_legion_1_1_min_reduction_3_01uint32__t_01_4.html", null ],
    [ "Legion::MinReduction< uint64_t >", "class_legion_1_1_min_reduction_3_01uint64__t_01_4.html", null ],
    [ "Legion::MinReduction< uint8_t >", "class_legion_1_1_min_reduction_3_01uint8__t_01_4.html", null ],
    [ "Legion::MustEpochLauncher", "struct_legion_1_1_must_epoch_launcher.html", null ],
    [ "Legion::OrReduction< T >", "class_legion_1_1_or_reduction.html", null ],
    [ "Legion::OrReduction< int16_t >", "class_legion_1_1_or_reduction_3_01int16__t_01_4.html", null ],
    [ "Legion::OrReduction< int32_t >", "class_legion_1_1_or_reduction_3_01int32__t_01_4.html", null ],
    [ "Legion::OrReduction< int64_t >", "class_legion_1_1_or_reduction_3_01int64__t_01_4.html", null ],
    [ "Legion::OrReduction< int8_t >", "class_legion_1_1_or_reduction_3_01int8__t_01_4.html", null ],
    [ "Legion::OrReduction< uint16_t >", "class_legion_1_1_or_reduction_3_01uint16__t_01_4.html", null ],
    [ "Legion::OrReduction< uint32_t >", "class_legion_1_1_or_reduction_3_01uint32__t_01_4.html", null ],
    [ "Legion::OrReduction< uint64_t >", "class_legion_1_1_or_reduction_3_01uint64__t_01_4.html", null ],
    [ "Legion::OrReduction< uint8_t >", "class_legion_1_1_or_reduction_3_01uint8__t_01_4.html", null ],
    [ "Legion::PaddingAccessor< FT, N, COORD_T, A, CHECK_BOUNDS >", "class_legion_1_1_padding_accessor.html", null ],
    [ "Legion::Mapping::Mapper::PartitionProfilingInfo", "struct_legion_1_1_mapping_1_1_mapper_1_1_partition_profiling_info.html", null ],
    [ "Legion::PhaseBarrier", "class_legion_1_1_phase_barrier.html", [
      [ "Legion::DynamicCollective", "class_legion_1_1_dynamic_collective.html", null ]
    ] ],
    [ "Legion::Mapping::PhysicalInstance", "class_legion_1_1_mapping_1_1_physical_instance.html", null ],
    [ "Legion::PieceIterator", "class_legion_1_1_piece_iterator.html", [
      [ "Legion::PieceIteratorT< DIM, coord_t >", "class_legion_1_1_piece_iterator_t.html", null ],
      [ "Legion::PieceIteratorT< DIM, COORD_T >", "class_legion_1_1_piece_iterator_t.html", null ]
    ] ],
    [ "Legion::PointInDomainIterator< DIM, COORD_T >", "class_legion_1_1_point_in_domain_iterator.html", null ],
    [ "Legion::PointInRectIterator< DIM, COORD_T >", "class_legion_1_1_point_in_rect_iterator.html", null ],
    [ "Legion::PointInRectIterator< DIM, coord_t >", "class_legion_1_1_point_in_rect_iterator.html", null ],
    [ "Legion::PointTransformFunctor", "class_legion_1_1_point_transform_functor.html", null ],
    [ "Legion::PoolBounds", "struct_legion_1_1_pool_bounds.html", null ],
    [ "Legion::Mapping::Mapper::PostMapInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_post_map_input.html", null ],
    [ "Legion::Mapping::Mapper::PostMapOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_post_map_output.html", null ],
    [ "Legion::Internal::Predicated< OP >", "class_legion_1_1_internal_1_1_predicated.html", null ],
    [ "Legion::PredicateLauncher", "struct_legion_1_1_predicate_launcher.html", null ],
    [ "Legion::Mapping::Mapper::PremapTaskInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_premap_task_input.html", null ],
    [ "Legion::Mapping::Mapper::PremapTaskOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_premap_task_output.html", null ],
    [ "Legion::ProcessorConstraint", "class_legion_1_1_processor_constraint.html", null ],
    [ "Legion::ProdReduction< T >", "class_legion_1_1_prod_reduction.html", null ],
    [ "Legion::ProdReduction< bool >", "class_legion_1_1_prod_reduction_3_01bool_01_4.html", null ],
    [ "Legion::ProdReduction< double >", "class_legion_1_1_prod_reduction_3_01double_01_4.html", null ],
    [ "Legion::ProdReduction< float >", "class_legion_1_1_prod_reduction_3_01float_01_4.html", null ],
    [ "Legion::ProdReduction< int16_t >", "class_legion_1_1_prod_reduction_3_01int16__t_01_4.html", null ],
    [ "Legion::ProdReduction< int32_t >", "class_legion_1_1_prod_reduction_3_01int32__t_01_4.html", null ],
    [ "Legion::ProdReduction< int64_t >", "class_legion_1_1_prod_reduction_3_01int64__t_01_4.html", null ],
    [ "Legion::ProdReduction< int8_t >", "class_legion_1_1_prod_reduction_3_01int8__t_01_4.html", null ],
    [ "Legion::ProdReduction< uint16_t >", "class_legion_1_1_prod_reduction_3_01uint16__t_01_4.html", null ],
    [ "Legion::ProdReduction< uint32_t >", "class_legion_1_1_prod_reduction_3_01uint32__t_01_4.html", null ],
    [ "Legion::ProdReduction< uint64_t >", "class_legion_1_1_prod_reduction_3_01uint64__t_01_4.html", null ],
    [ "Legion::ProdReduction< uint8_t >", "class_legion_1_1_prod_reduction_3_01uint8__t_01_4.html", null ],
    [ "Legion::Mapping::Utilities::MappingProfiler::Profile", "struct_legion_1_1_mapping_1_1_utilities_1_1_mapping_profiler_1_1_profile.html", null ],
    [ "Legion::Mapping::Utilities::MappingProfiler::ProfilingOption", "struct_legion_1_1_mapping_1_1_utilities_1_1_mapping_profiler_1_1_profiling_option.html", null ],
    [ "Legion::Mapping::ProfilingRequest", "class_legion_1_1_mapping_1_1_profiling_request.html", null ],
    [ "Legion::Mapping::ProfilingResponse", "class_legion_1_1_mapping_1_1_profiling_response.html", null ],
    [ "Legion::ProjectionFunctor", "class_legion_1_1_projection_functor.html", null ],
    [ "Legion::RectInDomainIterator< DIM, COORD_T >", "class_legion_1_1_rect_in_domain_iterator.html", null ],
    [ "Legion::RectInDomainIterator< DIM, coord_t >", "class_legion_1_1_rect_in_domain_iterator.html", null ],
    [ "Legion::ReductionAccessor< REDOP, EXCLUSIVE, N, COORD_T, A, CHECK_BOUNDS >", "class_legion_1_1_reduction_accessor.html", null ],
    [ "Legion::RegionRequirement", "struct_legion_1_1_region_requirement.html", [
      [ "Legion::Mapping::ShimMapper::RegionRequirement", "struct_legion_1_1_mapping_1_1_shim_mapper_1_1_region_requirement.html", null ],
      [ "Legion::OutputRequirement", "struct_legion_1_1_output_requirement.html", null ]
    ] ],
    [ "Legion::RegistrationCallbackArgs", "struct_legion_1_1_registration_callback_args.html", null ],
    [ "Legion::ReleaseLauncher", "struct_legion_1_1_release_launcher.html", null ],
    [ "Legion::Mapping::ReplayMapper::ReleaseMappingInfo", "struct_legion_1_1_mapping_1_1_replay_mapper_1_1_release_mapping_info.html", null ],
    [ "Legion::Mapping::Mapper::ReleaseProfilingInfo", "struct_legion_1_1_mapping_1_1_mapper_1_1_release_profiling_info.html", null ],
    [ "Legion::Mapping::Mapper::ReplicateTaskInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_replicate_task_input.html", null ],
    [ "Legion::Mapping::Mapper::ReplicateTaskOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_replicate_task_output.html", null ],
    [ "Legion::Mapping::ReplayMapper::RequirementMapping", "struct_legion_1_1_mapping_1_1_replay_mapper_1_1_requirement_mapping.html", null ],
    [ "Legion::ResourceConstraint", "class_legion_1_1_resource_constraint.html", null ],
    [ "Legion::Span< FT, PM >::reverse_iterator", "class_legion_1_1_span_1_1reverse__iterator.html", null ],
    [ "Legion::Runtime", "class_legion_1_1_runtime.html", null ],
    [ "Legion::ScaleTransform< M, N, T >", "struct_legion_1_1_scale_transform.html", null ],
    [ "Legion::Mapping::select_task_options_message", "struct_legion_1_1_mapping_1_1select__task__options__message.html", null ],
    [ "Legion::Mapping::Mapper::SelectCloseSrcInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_select_close_src_input.html", null ],
    [ "Legion::Mapping::Mapper::SelectCloseSrcOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_select_close_src_output.html", null ],
    [ "Legion::Mapping::Mapper::SelectCopySrcInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_select_copy_src_input.html", null ],
    [ "Legion::Mapping::Mapper::SelectCopySrcOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_select_copy_src_output.html", null ],
    [ "Legion::Mapping::Mapper::SelectInlineSrcInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_select_inline_src_input.html", null ],
    [ "Legion::Mapping::Mapper::SelectInlineSrcOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_select_inline_src_output.html", null ],
    [ "Legion::Mapping::Mapper::SelectMappingInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_select_mapping_input.html", null ],
    [ "Legion::Mapping::Mapper::SelectMappingOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_select_mapping_output.html", null ],
    [ "Legion::Mapping::Mapper::SelectPartitionProjectionInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_select_partition_projection_input.html", null ],
    [ "Legion::Mapping::Mapper::SelectPartitionProjectionOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_select_partition_projection_output.html", null ],
    [ "Legion::Mapping::Mapper::SelectPartitionSrcInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_select_partition_src_input.html", null ],
    [ "Legion::Mapping::Mapper::SelectPartitionSrcOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_select_partition_src_output.html", null ],
    [ "Legion::Mapping::Mapper::SelectReleaseSrcInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_select_release_src_input.html", null ],
    [ "Legion::Mapping::Mapper::SelectReleaseSrcOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_select_release_src_output.html", null ],
    [ "Legion::Mapping::Mapper::SelectShardingFunctorInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_select_sharding_functor_input.html", null ],
    [ "Legion::Mapping::Mapper::SelectShardingFunctorOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_select_sharding_functor_output.html", [
      [ "Legion::Mapping::Mapper::MustEpochShardingFunctorOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_must_epoch_sharding_functor_output.html", null ]
    ] ],
    [ "Legion::Mapping::Mapper::SelectStealingInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_select_stealing_input.html", null ],
    [ "Legion::Mapping::Mapper::SelectStealingOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_select_stealing_output.html", null ],
    [ "Legion::Mapping::Mapper::SelectTaskSrcInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_select_task_src_input.html", null ],
    [ "Legion::Mapping::Mapper::SelectTaskSrcOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_select_task_src_output.html", null ],
    [ "Legion::Mapping::Mapper::SelectTunableInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_select_tunable_input.html", null ],
    [ "Legion::Mapping::Mapper::SelectTunableOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_select_tunable_output.html", null ],
    [ "Legion::Mapping::Mapper::SelectVariantInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_select_variant_input.html", null ],
    [ "Legion::Mapping::Mapper::SelectVariantOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_select_variant_output.html", null ],
    [ "Legion::ShardingFunctor", "class_legion_1_1_sharding_functor.html", null ],
    [ "Legion::Mapping::Mapper::SliceTaskInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_slice_task_input.html", null ],
    [ "Legion::Mapping::Mapper::SliceTaskOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_slice_task_output.html", null ],
    [ "Legion::Span< FT, PM >", "class_legion_1_1_span.html", null ],
    [ "Legion::Span< FT, PM >", "class_legion_1_1_span.html", null ],
    [ "Legion::SpanIterator< PM, FT, DIM, COORD_T >", "class_legion_1_1_span_iterator.html", null ],
    [ "Legion::Mapping::Mapper::SpeculativeOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_speculative_output.html", null ],
    [ "Legion::Mapping::Mapper::StealRequestInput", "struct_legion_1_1_mapping_1_1_mapper_1_1_steal_request_input.html", null ],
    [ "Legion::Mapping::Mapper::StealRequestOutput", "struct_legion_1_1_mapping_1_1_mapper_1_1_steal_request_output.html", null ],
    [ "Legion::DomainPoint::STLComparator", "struct_legion_1_1_domain_point_1_1_s_t_l_comparator.html", null ],
    [ "std::streambuf", null, [
      [ "Legion::Exception", "class_legion_1_1_exception.html", null ]
    ] ],
    [ "Legion::SumReduction< T >", "class_legion_1_1_sum_reduction.html", null ],
    [ "Legion::SumReduction< bool >", "class_legion_1_1_sum_reduction_3_01bool_01_4.html", null ],
    [ "Legion::SumReduction< double >", "class_legion_1_1_sum_reduction_3_01double_01_4.html", null ],
    [ "Legion::SumReduction< float >", "class_legion_1_1_sum_reduction_3_01float_01_4.html", null ],
    [ "Legion::SumReduction< int16_t >", "class_legion_1_1_sum_reduction_3_01int16__t_01_4.html", null ],
    [ "Legion::SumReduction< int32_t >", "class_legion_1_1_sum_reduction_3_01int32__t_01_4.html", null ],
    [ "Legion::SumReduction< int64_t >", "class_legion_1_1_sum_reduction_3_01int64__t_01_4.html", null ],
    [ "Legion::SumReduction< int8_t >", "class_legion_1_1_sum_reduction_3_01int8__t_01_4.html", null ],
    [ "Legion::SumReduction< uint16_t >", "class_legion_1_1_sum_reduction_3_01uint16__t_01_4.html", null ],
    [ "Legion::SumReduction< uint32_t >", "class_legion_1_1_sum_reduction_3_01uint32__t_01_4.html", null ],
    [ "Legion::SumReduction< uint64_t >", "class_legion_1_1_sum_reduction_3_01uint64__t_01_4.html", null ],
    [ "Legion::SumReduction< uint8_t >", "class_legion_1_1_sum_reduction_3_01uint8__t_01_4.html", null ],
    [ "Legion::TaskConfigOptions", "struct_legion_1_1_task_config_options.html", null ],
    [ "Legion::Mapping::TaskGeneratorArguments", "struct_legion_1_1_mapping_1_1_task_generator_arguments.html", null ],
    [ "Legion::TaskLauncher", "struct_legion_1_1_task_launcher.html", null ],
    [ "Legion::TaskLayoutConstraintSet", "class_legion_1_1_task_layout_constraint_set.html", null ],
    [ "Legion::Mapping::ReplayMapper::TaskMappingInfo", "struct_legion_1_1_mapping_1_1_replay_mapper_1_1_task_mapping_info.html", null ],
    [ "Legion::Mapping::Mapper::TaskOptions", "struct_legion_1_1_mapping_1_1_mapper_1_1_task_options.html", null ],
    [ "Legion::Mapping::Mapper::TaskProfilingInfo", "struct_legion_1_1_mapping_1_1_mapper_1_1_task_profiling_info.html", null ],
    [ "Legion::Mapping::Mapper::TaskSlice", "struct_legion_1_1_mapping_1_1_mapper_1_1_task_slice.html", null ],
    [ "Legion::Mapping::ShimMapper::TaskVariantCollection", "class_legion_1_1_mapping_1_1_shim_mapper_1_1_task_variant_collection.html", null ],
    [ "Legion::TaskVariantRegistrar", "struct_legion_1_1_task_variant_registrar.html", null ],
    [ "Legion::TimingLauncher", "struct_legion_1_1_timing_launcher.html", null ],
    [ "Legion::TunableLauncher", "struct_legion_1_1_tunable_launcher.html", null ],
    [ "Legion::Mapping::ReplayMapper::TunableMapping", "struct_legion_1_1_mapping_1_1_replay_mapper_1_1_tunable_mapping.html", null ],
    [ "Legion::UnsafeFieldAccessor< typename, int, typename, typename >", "class_legion_1_1_unsafe_field_accessor.html", null ],
    [ "Legion::Unserializable", "class_legion_1_1_unserializable.html", [
      [ "Legion::ArgumentMap", "class_legion_1_1_argument_map.html", null ],
      [ "Legion::DeferredBuffer< T, DIM, COORD_T, CHECK_BOUNDS >", "class_legion_1_1_deferred_buffer.html", null ],
      [ "Legion::ExternalResources", "class_legion_1_1_external_resources.html", null ],
      [ "Legion::FieldAllocator", "class_legion_1_1_field_allocator.html", null ],
      [ "Legion::Future", "class_legion_1_1_future.html", null ],
      [ "Legion::FutureMap", "class_legion_1_1_future_map.html", null ],
      [ "Legion::LegionHandshake", "class_legion_1_1_legion_handshake.html", [
        [ "Legion::MPILegionHandshake", "class_legion_1_1_m_p_i_legion_handshake.html", null ]
      ] ],
      [ "Legion::OutputRegion", "class_legion_1_1_output_region.html", null ],
      [ "Legion::PhysicalRegion", "class_legion_1_1_physical_region.html", null ],
      [ "Legion::Predicate", "class_legion_1_1_predicate.html", null ],
      [ "Legion::StaticDependence", "struct_legion_1_1_static_dependence.html", null ],
      [ "Legion::UntypedBuffer", "class_legion_1_1_untyped_buffer.html", null ],
      [ "Legion::UntypedDeferredBuffer< COORD_T >", "class_legion_1_1_untyped_deferred_buffer.html", null ]
    ] ],
    [ "Legion::UntypedDeferredValue", "class_legion_1_1_untyped_deferred_value.html", [
      [ "Legion::DeferredValue< REDOP::RHS >", "class_legion_1_1_deferred_value.html", [
        [ "Legion::DeferredReduction< REDOP, EXCLUSIVE >", "class_legion_1_1_deferred_reduction.html", null ]
      ] ],
      [ "Legion::DeferredValue< T >", "class_legion_1_1_deferred_value.html", null ]
    ] ],
    [ "Legion::Internal::ValueBroadcast< T >", "class_legion_1_1_internal_1_1_value_broadcast.html", null ],
    [ "Legion::Mapping::ShimMapper::TaskVariantCollection::Variant", "class_legion_1_1_mapping_1_1_shim_mapper_1_1_task_variant_collection_1_1_variant.html", null ],
    [ "Legion::Mapping::DefaultMapper::VariantInfo", "struct_legion_1_1_mapping_1_1_default_mapper_1_1_variant_info.html", null ],
    [ "Legion::Mapping::Utilities::MappingProfiler::VariantProfile", "struct_legion_1_1_mapping_1_1_utilities_1_1_mapping_profiler_1_1_variant_profile.html", null ],
    [ "Legion::Warning", "class_legion_1_1_warning.html", null ],
    [ "Legion::XorReduction< T >", "class_legion_1_1_xor_reduction.html", null ],
    [ "Legion::XorReduction< bool >", "class_legion_1_1_xor_reduction_3_01bool_01_4.html", null ],
    [ "Legion::XorReduction< int16_t >", "class_legion_1_1_xor_reduction_3_01int16__t_01_4.html", null ],
    [ "Legion::XorReduction< int32_t >", "class_legion_1_1_xor_reduction_3_01int32__t_01_4.html", null ],
    [ "Legion::XorReduction< int64_t >", "class_legion_1_1_xor_reduction_3_01int64__t_01_4.html", null ],
    [ "Legion::XorReduction< int8_t >", "class_legion_1_1_xor_reduction_3_01int8__t_01_4.html", null ],
    [ "Legion::XorReduction< uint16_t >", "class_legion_1_1_xor_reduction_3_01uint16__t_01_4.html", null ],
    [ "Legion::XorReduction< uint32_t >", "class_legion_1_1_xor_reduction_3_01uint32__t_01_4.html", null ],
    [ "Legion::XorReduction< uint64_t >", "class_legion_1_1_xor_reduction_3_01uint64__t_01_4.html", null ],
    [ "Legion::XorReduction< uint8_t >", "class_legion_1_1_xor_reduction_3_01uint8__t_01_4.html", null ]
];