var namespace_legion =
[
    [ "Mapping", "namespace_legion_1_1_mapping.html", "namespace_legion_1_1_mapping" ],
    [ "Acquire", "class_legion_1_1_acquire.html", null ],
    [ "AcquireLauncher", "struct_legion_1_1_acquire_launcher.html", null ],
    [ "AffineTransform", "struct_legion_1_1_affine_transform.html", null ],
    [ "AlignmentConstraint", "class_legion_1_1_alignment_constraint.html", null ],
    [ "AndReduction", "class_legion_1_1_and_reduction.html", null ],
    [ "AndReduction< int16_t >", "class_legion_1_1_and_reduction_3_01int16__t_01_4.html", null ],
    [ "AndReduction< int32_t >", "class_legion_1_1_and_reduction_3_01int32__t_01_4.html", null ],
    [ "AndReduction< int64_t >", "class_legion_1_1_and_reduction_3_01int64__t_01_4.html", null ],
    [ "AndReduction< int8_t >", "class_legion_1_1_and_reduction_3_01int8__t_01_4.html", null ],
    [ "AndReduction< uint16_t >", "class_legion_1_1_and_reduction_3_01uint16__t_01_4.html", null ],
    [ "AndReduction< uint32_t >", "class_legion_1_1_and_reduction_3_01uint32__t_01_4.html", null ],
    [ "AndReduction< uint64_t >", "class_legion_1_1_and_reduction_3_01uint64__t_01_4.html", null ],
    [ "AndReduction< uint8_t >", "class_legion_1_1_and_reduction_3_01uint8__t_01_4.html", null ],
    [ "ArgumentMap", "class_legion_1_1_argument_map.html", "class_legion_1_1_argument_map" ],
    [ "AttachLauncher", "struct_legion_1_1_attach_launcher.html", null ],
    [ "Close", "class_legion_1_1_close.html", null ],
    [ "ColocationConstraint", "class_legion_1_1_colocation_constraint.html", null ],
    [ "ConcurrentColoringFunctor", "class_legion_1_1_concurrent_coloring_functor.html", null ],
    [ "Copy", "class_legion_1_1_copy.html", null ],
    [ "CopyLauncher", "struct_legion_1_1_copy_launcher.html", null ],
    [ "DeferredBuffer", "class_legion_1_1_deferred_buffer.html", null ],
    [ "DeferredBufferRequest", "struct_legion_1_1_deferred_buffer_request.html", null ],
    [ "DeferredReduction", "class_legion_1_1_deferred_reduction.html", null ],
    [ "DeferredValue", "class_legion_1_1_deferred_value.html", null ],
    [ "DeferredValueRequest", "struct_legion_1_1_deferred_value_request.html", null ],
    [ "DiffReduction", "class_legion_1_1_diff_reduction.html", null ],
    [ "DiffReduction< double >", "class_legion_1_1_diff_reduction_3_01double_01_4.html", null ],
    [ "DiffReduction< float >", "class_legion_1_1_diff_reduction_3_01float_01_4.html", null ],
    [ "DiffReduction< int16_t >", "class_legion_1_1_diff_reduction_3_01int16__t_01_4.html", null ],
    [ "DiffReduction< int32_t >", "class_legion_1_1_diff_reduction_3_01int32__t_01_4.html", null ],
    [ "DiffReduction< int64_t >", "class_legion_1_1_diff_reduction_3_01int64__t_01_4.html", null ],
    [ "DiffReduction< int8_t >", "class_legion_1_1_diff_reduction_3_01int8__t_01_4.html", null ],
    [ "DiffReduction< uint16_t >", "class_legion_1_1_diff_reduction_3_01uint16__t_01_4.html", null ],
    [ "DiffReduction< uint32_t >", "class_legion_1_1_diff_reduction_3_01uint32__t_01_4.html", null ],
    [ "DiffReduction< uint64_t >", "class_legion_1_1_diff_reduction_3_01uint64__t_01_4.html", null ],
    [ "DiffReduction< uint8_t >", "class_legion_1_1_diff_reduction_3_01uint8__t_01_4.html", null ],
    [ "DimensionConstraint", "class_legion_1_1_dimension_constraint.html", null ],
    [ "DiscardLauncher", "struct_legion_1_1_discard_launcher.html", null ],
    [ "DivReduction", "class_legion_1_1_div_reduction.html", null ],
    [ "DivReduction< double >", "class_legion_1_1_div_reduction_3_01double_01_4.html", null ],
    [ "DivReduction< float >", "class_legion_1_1_div_reduction_3_01float_01_4.html", null ],
    [ "DivReduction< int16_t >", "class_legion_1_1_div_reduction_3_01int16__t_01_4.html", null ],
    [ "DivReduction< int32_t >", "class_legion_1_1_div_reduction_3_01int32__t_01_4.html", null ],
    [ "DivReduction< int64_t >", "class_legion_1_1_div_reduction_3_01int64__t_01_4.html", null ],
    [ "DivReduction< int8_t >", "class_legion_1_1_div_reduction_3_01int8__t_01_4.html", null ],
    [ "DivReduction< uint16_t >", "class_legion_1_1_div_reduction_3_01uint16__t_01_4.html", null ],
    [ "DivReduction< uint32_t >", "class_legion_1_1_div_reduction_3_01uint32__t_01_4.html", null ],
    [ "DivReduction< uint64_t >", "class_legion_1_1_div_reduction_3_01uint64__t_01_4.html", null ],
    [ "DivReduction< uint8_t >", "class_legion_1_1_div_reduction_3_01uint8__t_01_4.html", null ],
    [ "Domain", "class_legion_1_1_domain.html", "class_legion_1_1_domain" ],
    [ "DomainAffineTransform", "class_legion_1_1_domain_affine_transform.html", null ],
    [ "DomainPoint", "class_legion_1_1_domain_point.html", "class_legion_1_1_domain_point" ],
    [ "DomainScaleTransform", "class_legion_1_1_domain_scale_transform.html", null ],
    [ "DomainTransform", "class_legion_1_1_domain_transform.html", null ],
    [ "DynamicCollective", "class_legion_1_1_dynamic_collective.html", null ],
    [ "Error", "class_legion_1_1_error.html", null ],
    [ "Exception", "class_legion_1_1_exception.html", null ],
    [ "ExceptionHandler", "class_legion_1_1_exception_handler.html", null ],
    [ "ExecutionConstraintSet", "class_legion_1_1_execution_constraint_set.html", null ],
    [ "ExternalResources", "class_legion_1_1_external_resources.html", null ],
    [ "Fatal", "class_legion_1_1_fatal.html", null ],
    [ "FieldAccessor", "class_legion_1_1_field_accessor.html", null ],
    [ "FieldAllocator", "class_legion_1_1_field_allocator.html", "class_legion_1_1_field_allocator" ],
    [ "FieldConstraint", "class_legion_1_1_field_constraint.html", null ],
    [ "FieldSpace", "class_legion_1_1_field_space.html", "class_legion_1_1_field_space" ],
    [ "FieldSpaceRequirement", "struct_legion_1_1_field_space_requirement.html", null ],
    [ "Fill", "class_legion_1_1_fill.html", null ],
    [ "FillLauncher", "struct_legion_1_1_fill_launcher.html", null ],
    [ "Future", "class_legion_1_1_future.html", "class_legion_1_1_future" ],
    [ "FutureFunctor", "class_legion_1_1_future_functor.html", null ],
    [ "FutureMap", "class_legion_1_1_future_map.html", "class_legion_1_1_future_map" ],
    [ "Grant", "class_legion_1_1_grant.html", null ],
    [ "IndexAttachLauncher", "struct_legion_1_1_index_attach_launcher.html", null ],
    [ "IndexCopyLauncher", "struct_legion_1_1_index_copy_launcher.html", null ],
    [ "IndexFillLauncher", "struct_legion_1_1_index_fill_launcher.html", null ],
    [ "IndexPartition", "class_legion_1_1_index_partition.html", null ],
    [ "IndexPartitionT", "class_legion_1_1_index_partition_t.html", null ],
    [ "IndexSpace", "class_legion_1_1_index_space.html", "class_legion_1_1_index_space" ],
    [ "IndexSpaceRequirement", "struct_legion_1_1_index_space_requirement.html", null ],
    [ "IndexSpaceT", "class_legion_1_1_index_space_t.html", null ],
    [ "IndexTaskLauncher", "struct_legion_1_1_index_task_launcher.html", null ],
    [ "InlineLauncher", "struct_legion_1_1_inline_launcher.html", null ],
    [ "InlineMapping", "class_legion_1_1_inline_mapping.html", null ],
    [ "InputArgs", "struct_legion_1_1_input_args.html", null ],
    [ "ISAConstraint", "class_legion_1_1_i_s_a_constraint.html", null ],
    [ "LaunchConstraint", "class_legion_1_1_launch_constraint.html", null ],
    [ "LayoutConstraint", "class_legion_1_1_layout_constraint.html", null ],
    [ "LayoutConstraintRegistrar", "struct_legion_1_1_layout_constraint_registrar.html", null ],
    [ "LayoutConstraintSet", "class_legion_1_1_layout_constraint_set.html", null ],
    [ "LegionHandshake", "class_legion_1_1_legion_handshake.html", "class_legion_1_1_legion_handshake" ],
    [ "Lock", "class_legion_1_1_lock.html", null ],
    [ "LockRequest", "struct_legion_1_1_lock_request.html", null ],
    [ "LogicalPartition", "class_legion_1_1_logical_partition.html", "class_legion_1_1_logical_partition" ],
    [ "LogicalPartitionT", "class_legion_1_1_logical_partition_t.html", null ],
    [ "LogicalRegion", "class_legion_1_1_logical_region.html", "class_legion_1_1_logical_region" ],
    [ "LogicalRegionT", "class_legion_1_1_logical_region_t.html", null ],
    [ "Mappable", "class_legion_1_1_mappable.html", null ],
    [ "MaxReduction", "class_legion_1_1_max_reduction.html", null ],
    [ "MaxReduction< bool >", "class_legion_1_1_max_reduction_3_01bool_01_4.html", null ],
    [ "MaxReduction< double >", "class_legion_1_1_max_reduction_3_01double_01_4.html", null ],
    [ "MaxReduction< float >", "class_legion_1_1_max_reduction_3_01float_01_4.html", null ],
    [ "MaxReduction< int16_t >", "class_legion_1_1_max_reduction_3_01int16__t_01_4.html", null ],
    [ "MaxReduction< int32_t >", "class_legion_1_1_max_reduction_3_01int32__t_01_4.html", null ],
    [ "MaxReduction< int64_t >", "class_legion_1_1_max_reduction_3_01int64__t_01_4.html", null ],
    [ "MaxReduction< int8_t >", "class_legion_1_1_max_reduction_3_01int8__t_01_4.html", null ],
    [ "MaxReduction< uint16_t >", "class_legion_1_1_max_reduction_3_01uint16__t_01_4.html", null ],
    [ "MaxReduction< uint32_t >", "class_legion_1_1_max_reduction_3_01uint32__t_01_4.html", null ],
    [ "MaxReduction< uint64_t >", "class_legion_1_1_max_reduction_3_01uint64__t_01_4.html", null ],
    [ "MaxReduction< uint8_t >", "class_legion_1_1_max_reduction_3_01uint8__t_01_4.html", null ],
    [ "MemoryConstraint", "class_legion_1_1_memory_constraint.html", null ],
    [ "MinReduction", "class_legion_1_1_min_reduction.html", null ],
    [ "MinReduction< bool >", "class_legion_1_1_min_reduction_3_01bool_01_4.html", null ],
    [ "MinReduction< double >", "class_legion_1_1_min_reduction_3_01double_01_4.html", null ],
    [ "MinReduction< float >", "class_legion_1_1_min_reduction_3_01float_01_4.html", null ],
    [ "MinReduction< int16_t >", "class_legion_1_1_min_reduction_3_01int16__t_01_4.html", null ],
    [ "MinReduction< int32_t >", "class_legion_1_1_min_reduction_3_01int32__t_01_4.html", null ],
    [ "MinReduction< int64_t >", "class_legion_1_1_min_reduction_3_01int64__t_01_4.html", null ],
    [ "MinReduction< int8_t >", "class_legion_1_1_min_reduction_3_01int8__t_01_4.html", null ],
    [ "MinReduction< uint16_t >", "class_legion_1_1_min_reduction_3_01uint16__t_01_4.html", null ],
    [ "MinReduction< uint32_t >", "class_legion_1_1_min_reduction_3_01uint32__t_01_4.html", null ],
    [ "MinReduction< uint64_t >", "class_legion_1_1_min_reduction_3_01uint64__t_01_4.html", null ],
    [ "MinReduction< uint8_t >", "class_legion_1_1_min_reduction_3_01uint8__t_01_4.html", null ],
    [ "MPILegionHandshake", "class_legion_1_1_m_p_i_legion_handshake.html", "class_legion_1_1_m_p_i_legion_handshake" ],
    [ "MustEpoch", "class_legion_1_1_must_epoch.html", null ],
    [ "MustEpochLauncher", "struct_legion_1_1_must_epoch_launcher.html", null ],
    [ "OffsetConstraint", "class_legion_1_1_offset_constraint.html", null ],
    [ "OrderingConstraint", "class_legion_1_1_ordering_constraint.html", null ],
    [ "OrReduction", "class_legion_1_1_or_reduction.html", null ],
    [ "OrReduction< int16_t >", "class_legion_1_1_or_reduction_3_01int16__t_01_4.html", null ],
    [ "OrReduction< int32_t >", "class_legion_1_1_or_reduction_3_01int32__t_01_4.html", null ],
    [ "OrReduction< int64_t >", "class_legion_1_1_or_reduction_3_01int64__t_01_4.html", null ],
    [ "OrReduction< int8_t >", "class_legion_1_1_or_reduction_3_01int8__t_01_4.html", null ],
    [ "OrReduction< uint16_t >", "class_legion_1_1_or_reduction_3_01uint16__t_01_4.html", null ],
    [ "OrReduction< uint32_t >", "class_legion_1_1_or_reduction_3_01uint32__t_01_4.html", null ],
    [ "OrReduction< uint64_t >", "class_legion_1_1_or_reduction_3_01uint64__t_01_4.html", null ],
    [ "OrReduction< uint8_t >", "class_legion_1_1_or_reduction_3_01uint8__t_01_4.html", null ],
    [ "OutputRegion", "class_legion_1_1_output_region.html", null ],
    [ "OutputRequirement", "struct_legion_1_1_output_requirement.html", "struct_legion_1_1_output_requirement" ],
    [ "PaddingAccessor", "class_legion_1_1_padding_accessor.html", null ],
    [ "PaddingConstraint", "class_legion_1_1_padding_constraint.html", null ],
    [ "Partition", "class_legion_1_1_partition.html", null ],
    [ "PhaseBarrier", "class_legion_1_1_phase_barrier.html", null ],
    [ "PhysicalRegion", "class_legion_1_1_physical_region.html", "class_legion_1_1_physical_region" ],
    [ "PieceIterator", "class_legion_1_1_piece_iterator.html", null ],
    [ "PieceIteratorT", "class_legion_1_1_piece_iterator_t.html", null ],
    [ "PointerConstraint", "class_legion_1_1_pointer_constraint.html", null ],
    [ "PointInDomainIterator", "class_legion_1_1_point_in_domain_iterator.html", null ],
    [ "PointInRectIterator", "class_legion_1_1_point_in_rect_iterator.html", null ],
    [ "PointTransformFunctor", "class_legion_1_1_point_transform_functor.html", null ],
    [ "PoolBounds", "struct_legion_1_1_pool_bounds.html", null ],
    [ "Predicate", "class_legion_1_1_predicate.html", null ],
    [ "PredicateLauncher", "struct_legion_1_1_predicate_launcher.html", null ],
    [ "ProcessorConstraint", "class_legion_1_1_processor_constraint.html", null ],
    [ "ProdReduction", "class_legion_1_1_prod_reduction.html", null ],
    [ "ProdReduction< bool >", "class_legion_1_1_prod_reduction_3_01bool_01_4.html", null ],
    [ "ProdReduction< double >", "class_legion_1_1_prod_reduction_3_01double_01_4.html", null ],
    [ "ProdReduction< float >", "class_legion_1_1_prod_reduction_3_01float_01_4.html", null ],
    [ "ProdReduction< int16_t >", "class_legion_1_1_prod_reduction_3_01int16__t_01_4.html", null ],
    [ "ProdReduction< int32_t >", "class_legion_1_1_prod_reduction_3_01int32__t_01_4.html", null ],
    [ "ProdReduction< int64_t >", "class_legion_1_1_prod_reduction_3_01int64__t_01_4.html", null ],
    [ "ProdReduction< int8_t >", "class_legion_1_1_prod_reduction_3_01int8__t_01_4.html", null ],
    [ "ProdReduction< uint16_t >", "class_legion_1_1_prod_reduction_3_01uint16__t_01_4.html", null ],
    [ "ProdReduction< uint32_t >", "class_legion_1_1_prod_reduction_3_01uint32__t_01_4.html", null ],
    [ "ProdReduction< uint64_t >", "class_legion_1_1_prod_reduction_3_01uint64__t_01_4.html", null ],
    [ "ProdReduction< uint8_t >", "class_legion_1_1_prod_reduction_3_01uint8__t_01_4.html", null ],
    [ "ProjectionFunctor", "class_legion_1_1_projection_functor.html", "class_legion_1_1_projection_functor" ],
    [ "RectInDomainIterator", "class_legion_1_1_rect_in_domain_iterator.html", null ],
    [ "ReductionAccessor", "class_legion_1_1_reduction_accessor.html", null ],
    [ "RegionRequirement", "struct_legion_1_1_region_requirement.html", "struct_legion_1_1_region_requirement" ],
    [ "RegistrationCallbackArgs", "struct_legion_1_1_registration_callback_args.html", null ],
    [ "Release", "class_legion_1_1_release.html", null ],
    [ "ReleaseLauncher", "struct_legion_1_1_release_launcher.html", null ],
    [ "ResourceConstraint", "class_legion_1_1_resource_constraint.html", null ],
    [ "Runtime", "class_legion_1_1_runtime.html", "class_legion_1_1_runtime" ],
    [ "ScaleTransform", "struct_legion_1_1_scale_transform.html", null ],
    [ "ShardingFunctor", "class_legion_1_1_sharding_functor.html", null ],
    [ "Span", "class_legion_1_1_span.html", "class_legion_1_1_span" ],
    [ "SpanIterator", "class_legion_1_1_span_iterator.html", null ],
    [ "SpecializedConstraint", "class_legion_1_1_specialized_constraint.html", null ],
    [ "StaticDependence", "struct_legion_1_1_static_dependence.html", null ],
    [ "SumReduction", "class_legion_1_1_sum_reduction.html", null ],
    [ "SumReduction< bool >", "class_legion_1_1_sum_reduction_3_01bool_01_4.html", null ],
    [ "SumReduction< double >", "class_legion_1_1_sum_reduction_3_01double_01_4.html", null ],
    [ "SumReduction< float >", "class_legion_1_1_sum_reduction_3_01float_01_4.html", null ],
    [ "SumReduction< int16_t >", "class_legion_1_1_sum_reduction_3_01int16__t_01_4.html", null ],
    [ "SumReduction< int32_t >", "class_legion_1_1_sum_reduction_3_01int32__t_01_4.html", null ],
    [ "SumReduction< int64_t >", "class_legion_1_1_sum_reduction_3_01int64__t_01_4.html", null ],
    [ "SumReduction< int8_t >", "class_legion_1_1_sum_reduction_3_01int8__t_01_4.html", null ],
    [ "SumReduction< uint16_t >", "class_legion_1_1_sum_reduction_3_01uint16__t_01_4.html", null ],
    [ "SumReduction< uint32_t >", "class_legion_1_1_sum_reduction_3_01uint32__t_01_4.html", null ],
    [ "SumReduction< uint64_t >", "class_legion_1_1_sum_reduction_3_01uint64__t_01_4.html", null ],
    [ "SumReduction< uint8_t >", "class_legion_1_1_sum_reduction_3_01uint8__t_01_4.html", null ],
    [ "Task", "class_legion_1_1_task.html", null ],
    [ "TaskConfigOptions", "struct_legion_1_1_task_config_options.html", null ],
    [ "TaskLauncher", "struct_legion_1_1_task_launcher.html", null ],
    [ "TaskLayoutConstraintSet", "class_legion_1_1_task_layout_constraint_set.html", null ],
    [ "TaskVariantRegistrar", "struct_legion_1_1_task_variant_registrar.html", null ],
    [ "TilingConstraint", "class_legion_1_1_tiling_constraint.html", null ],
    [ "TimingLauncher", "struct_legion_1_1_timing_launcher.html", null ],
    [ "TunableLauncher", "struct_legion_1_1_tunable_launcher.html", null ],
    [ "UnsafeFieldAccessor", "class_legion_1_1_unsafe_field_accessor.html", null ],
    [ "Unserializable", "class_legion_1_1_unserializable.html", null ],
    [ "UntypedBuffer", "class_legion_1_1_untyped_buffer.html", null ],
    [ "UntypedDeferredBuffer", "class_legion_1_1_untyped_deferred_buffer.html", null ],
    [ "UntypedDeferredValue", "class_legion_1_1_untyped_deferred_value.html", null ],
    [ "Warning", "class_legion_1_1_warning.html", null ],
    [ "XorReduction", "class_legion_1_1_xor_reduction.html", null ],
    [ "XorReduction< bool >", "class_legion_1_1_xor_reduction_3_01bool_01_4.html", null ],
    [ "XorReduction< int16_t >", "class_legion_1_1_xor_reduction_3_01int16__t_01_4.html", null ],
    [ "XorReduction< int32_t >", "class_legion_1_1_xor_reduction_3_01int32__t_01_4.html", null ],
    [ "XorReduction< int64_t >", "class_legion_1_1_xor_reduction_3_01int64__t_01_4.html", null ],
    [ "XorReduction< int8_t >", "class_legion_1_1_xor_reduction_3_01int8__t_01_4.html", null ],
    [ "XorReduction< uint16_t >", "class_legion_1_1_xor_reduction_3_01uint16__t_01_4.html", null ],
    [ "XorReduction< uint32_t >", "class_legion_1_1_xor_reduction_3_01uint32__t_01_4.html", null ],
    [ "XorReduction< uint64_t >", "class_legion_1_1_xor_reduction_3_01uint64__t_01_4.html", null ],
    [ "XorReduction< uint8_t >", "class_legion_1_1_xor_reduction_3_01uint8__t_01_4.html", null ]
];